import Foundation

struct EmojiCategoryModel: Identifiable {
    let id = UUID()
    let name: String
    let icon: String
    let items: [EmojiWordModel]
}

struct EmojiWordModel: Identifiable {
    let id = UUID()
    let emoji: String
    let italian: String
    let french: String
}

struct EmojiDataSource {
    static func getAllCategories() -> [EmojiCategoryModel] {
        return [
            EmojiCategoryModel(name: "Émotions", icon: "😊", items: [
                EmojiWordModel(emoji: "😀", italian: "contento", french: "content"),
                EmojiWordModel(emoji: "😢", italian: "triste", french: "triste"),
                EmojiWordModel(emoji: "😡", italian: "arrabbiato", french: "en colère"),
                EmojiWordModel(emoji: "😱", italian: "spaventato", french: "effrayé"),
                EmojiWordModel(emoji: "😍", italian: "innamorato", french: "amoureux"),
                EmojiWordModel(emoji: "🤔", italian: "pensieroso", french: "pensif"),
                EmojiWordModel(emoji: "😴", italian: "stanco", french: "fatigué"),
                EmojiWordModel(emoji: "🤢", italian: "malato", french: "malade"),
                EmojiWordModel(emoji: "😎", italian: "figo", french: "cool"),
                EmojiWordModel(emoji: "🥳", italian: "festoso", french: "festif"),
                EmojiWordModel(emoji: "😤", italian: "frustrato", french: "frustré"),
                EmojiWordModel(emoji: "🥺", italian: "implorante", french: "suppliant"),
                EmojiWordModel(emoji: "🤩", italian: "impressionato", french: "impressionné"),
                EmojiWordModel(emoji: "😭", italian: "in lacrime", french: "en larmes"),
                EmojiWordModel(emoji: "😇", italian: "buono", french: "sage"),
                EmojiWordModel(emoji: "🤗", italian: "abbraccio", french: "câlin"),
                EmojiWordModel(emoji: "😏", italian: "furbo", french: "malin"),
                EmojiWordModel(emoji: "🥱", italian: "sbadigliante", french: "bâillant"),
                EmojiWordModel(emoji: "😵", italian: "stordito", french: "étourdi"),
                EmojiWordModel(emoji: "🤪", italian: "pazzo", french: "fou")
            ]),
            EmojiCategoryModel(name: "Nourriture", icon: "🍕", items: [
                EmojiWordModel(emoji: "🍕", italian: "la pizza", french: "pizza"),
                EmojiWordModel(emoji: "🍝", italian: "la pasta", french: "pâtes"),
                EmojiWordModel(emoji: "🍞", italian: "il pane", french: "pain"),
                EmojiWordModel(emoji: "🧀", italian: "il formaggio", french: "fromage"),
                EmojiWordModel(emoji: "🍷", italian: "il vino", french: "vin"),
                EmojiWordModel(emoji: "☕", italian: "il caffè", french: "café"),
                EmojiWordModel(emoji: "🍦", italian: "il gelato", french: "glace"),
                EmojiWordModel(emoji: "🍎", italian: "la mela", french: "pomme"),
                EmojiWordModel(emoji: "🍊", italian: "l'arancia", french: "orange"),
                EmojiWordModel(emoji: "🍋", italian: "il limone", french: "citron"),
                EmojiWordModel(emoji: "🍇", italian: "l'uva", french: "raisin"),
                EmojiWordModel(emoji: "🍓", italian: "la fragola", french: "fraise"),
                EmojiWordModel(emoji: "🥕", italian: "la carota", french: "carotte"),
                EmojiWordModel(emoji: "🥒", italian: "il cetriolo", french: "concombre"),
                EmojiWordModel(emoji: "🍅", italian: "il pomodoro", french: "tomate"),
                EmojiWordModel(emoji: "🥚", italian: "l'uovo", french: "œuf"),
                EmojiWordModel(emoji: "🍌", italian: "la banana", french: "banane"),
                EmojiWordModel(emoji: "🍰", italian: "la torta", french: "gâteau"),
                EmojiWordModel(emoji: "🍟", italian: "le patatine", french: "frites"),
                EmojiWordModel(emoji: "🍔", italian: "l'hamburger", french: "hamburger"),
                EmojiWordModel(emoji: "🌮", italian: "il taco", french: "taco"),
                EmojiWordModel(emoji: "🍿", italian: "i popcorn", french: "pop-corn"),
                EmojiWordModel(emoji: "🍩", italian: "la ciambella", french: "donut"),
                EmojiWordModel(emoji: "🍪", italian: "il biscotto", french: "cookie"),
                EmojiWordModel(emoji: "🥐", italian: "il cornetto", french: "croissant")
            ]),
            EmojiCategoryModel(name: "Animaux", icon: "🐱", items: [
                EmojiWordModel(emoji: "🐱", italian: "il gatto", french: "chat"),
                EmojiWordModel(emoji: "🐶", italian: "il cane", french: "chien"),
                EmojiWordModel(emoji: "🐦", italian: "l'uccello", french: "oiseau"),
                EmojiWordModel(emoji: "🐟", italian: "il pesce", french: "poisson"),
                EmojiWordModel(emoji: "🐴", italian: "il cavallo", french: "cheval"),
                EmojiWordModel(emoji: "🐄", italian: "la mucca", french: "vache"),
                EmojiWordModel(emoji: "🐷", italian: "il maiale", french: "cochon"),
                EmojiWordModel(emoji: "🐑", italian: "la pecora", french: "mouton"),
                EmojiWordModel(emoji: "🐓", italian: "il gallo", french: "coq"),
                EmojiWordModel(emoji: "🦋", italian: "la farfalla", french: "papillon"),
                EmojiWordModel(emoji: "🐝", italian: "l'ape", french: "abeille"),
                EmojiWordModel(emoji: "🐢", italian: "la tartaruga", french: "tortue"),
                EmojiWordModel(emoji: "🐘", italian: "l'elefante", french: "éléphant"),
                EmojiWordModel(emoji: "🦁", italian: "il leone", french: "lion"),
                EmojiWordModel(emoji: "🐻", italian: "l'orso", french: "ours"),
                EmojiWordModel(emoji: "🐰", italian: "il coniglio", french: "lapin"),
                EmojiWordModel(emoji: "🦊", italian: "la volpe", french: "renard"),
                EmojiWordModel(emoji: "🐯", italian: "la tigre", french: "tigre"),
                EmojiWordModel(emoji: "🦒", italian: "la giraffa", french: "girafe"),
                EmojiWordModel(emoji: "🐼", italian: "il panda", french: "panda"),
                EmojiWordModel(emoji: "🐨", italian: "il koala", french: "koala"),
                EmojiWordModel(emoji: "🦘", italian: "il canguro", french: "kangourou"),
                EmojiWordModel(emoji: "🐸", italian: "la rana", french: "grenouille"),
                EmojiWordModel(emoji: "🐍", italian: "il serpente", french: "serpent")
            ]),
            EmojiCategoryModel(name: "Nature", icon: "🌳", items: [
                EmojiWordModel(emoji: "🌳", italian: "l'albero", french: "arbre"),
                EmojiWordModel(emoji: "🌸", italian: "il fiore", french: "fleur"),
                EmojiWordModel(emoji: "🌞", italian: "il sole", french: "soleil"),
                EmojiWordModel(emoji: "🌙", italian: "la luna", french: "lune"),
                EmojiWordModel(emoji: "⭐", italian: "la stella", french: "étoile"),
                EmojiWordModel(emoji: "🌧️", italian: "la pioggia", french: "pluie"),
                EmojiWordModel(emoji: "❄️", italian: "la neve", french: "neige"),
                EmojiWordModel(emoji: "🌈", italian: "l'arcobaleno", french: "arc-en-ciel"),
                EmojiWordModel(emoji: "🌊", italian: "l'onda", french: "vague"),
                EmojiWordModel(emoji: "⛰️", italian: "la montagna", french: "montagne"),
                EmojiWordModel(emoji: "🏝️", italian: "l'isola", french: "île"),
                EmojiWordModel(emoji: "🌴", italian: "la palma", french: "palmier"),
                EmojiWordModel(emoji: "🌵", italian: "il cactus", french: "cactus"),
                EmojiWordModel(emoji: "🌺", italian: "l'ibisco", french: "hibiscus"),
                EmojiWordModel(emoji: "🌻", italian: "il girasole", french: "tournesol"),
                EmojiWordModel(emoji: "🌹", italian: "la rosa", french: "rose"),
                EmojiWordModel(emoji: "🍀", italian: "il trifoglio", french: "trèfle"),
                EmojiWordModel(emoji: "🍁", italian: "l'acero", french: "érable"),
                EmojiWordModel(emoji: "🌾", italian: "il grano", french: "blé")
            ]),
            EmojiCategoryModel(name: "Transports", icon: "🚗", items: [
                EmojiWordModel(emoji: "🚗", italian: "la macchina", french: "voiture"),
                EmojiWordModel(emoji: "🚌", italian: "l'autobus", french: "bus"),
                EmojiWordModel(emoji: "🚂", italian: "il treno", french: "train"),
                EmojiWordModel(emoji: "✈️", italian: "l'aereo", french: "avion"),
                EmojiWordModel(emoji: "🚢", italian: "la nave", french: "bateau"),
                EmojiWordModel(emoji: "🚲", italian: "la bicicletta", french: "vélo"),
                EmojiWordModel(emoji: "🏍️", italian: "la moto", french: "moto"),
                EmojiWordModel(emoji: "🚁", italian: "l'elicottero", french: "hélicoptère"),
                EmojiWordModel(emoji: "🚀", italian: "il razzo", french: "fusée"),
                EmojiWordModel(emoji: "🛴", italian: "il monopattino", french: "trottinette"),
                EmojiWordModel(emoji: "🚕", italian: "il taxi", french: "taxi"),
                EmojiWordModel(emoji: "🚙", italian: "il SUV", french: "SUV"),
                EmojiWordModel(emoji: "🚎", italian: "il filobus", french: "trolleybus")
            ]),
            EmojiCategoryModel(name: "Objets", icon: "📱", items: [
                EmojiWordModel(emoji: "📱", italian: "il telefono", french: "téléphone"),
                EmojiWordModel(emoji: "💻", italian: "il computer", french: "ordinateur"),
                EmojiWordModel(emoji: "📺", italian: "la televisione", french: "télévision"),
                EmojiWordModel(emoji: "📷", italian: "la macchina fotografica", french: "appareil photo"),
                EmojiWordModel(emoji: "🎸", italian: "la chitarra", french: "guitare"),
                EmojiWordModel(emoji: "🎹", italian: "il pianoforte", french: "piano"),
                EmojiWordModel(emoji: "📚", italian: "i libri", french: "livres"),
                EmojiWordModel(emoji: "✏️", italian: "la matita", french: "crayon"),
                EmojiWordModel(emoji: "🔑", italian: "la chiave", french: "clé"),
                EmojiWordModel(emoji: "💡", italian: "la lampadina", french: "ampoule"),
                EmojiWordModel(emoji: "🕶️", italian: "gli occhiali", french: "lunettes"),
                EmojiWordModel(emoji: "👜", italian: "la borsa", french: "sac"),
                EmojiWordModel(emoji: "⌚", italian: "l'orologio", french: "montre"),
                EmojiWordModel(emoji: "💍", italian: "l'anello", french: "bague"),
                EmojiWordModel(emoji: "👑", italian: "la corona", french: "couronne"),
                EmojiWordModel(emoji: "🎁", italian: "il regalo", french: "cadeau"),
                EmojiWordModel(emoji: "🎈", italian: "il palloncino", french: "ballon"),
                EmojiWordModel(emoji: "🔦", italian: "la torcia", french: "lampe")
            ]),
            EmojiCategoryModel(name: "Sports", icon: "⚽", items: [
                EmojiWordModel(emoji: "⚽", italian: "il calcio", french: "football"),
                EmojiWordModel(emoji: "🏀", italian: "la pallacanestro", french: "basketball"),
                EmojiWordModel(emoji: "🎾", italian: "il tennis", french: "tennis"),
                EmojiWordModel(emoji: "🏊", italian: "il nuoto", french: "natation"),
                EmojiWordModel(emoji: "🚴", italian: "il ciclismo", french: "cyclisme"),
                EmojiWordModel(emoji: "⛷️", italian: "lo sci", french: "ski"),
                EmojiWordModel(emoji: "🏃", italian: "la corsa", french: "course"),
                EmojiWordModel(emoji: "🥊", italian: "la boxe", french: "boxe"),
                EmojiWordModel(emoji: "🏐", italian: "la pallavolo", french: "volleyball"),
                EmojiWordModel(emoji: "🏈", italian: "il football americano", french: "football américain"),
                EmojiWordModel(emoji: "⛳", italian: "il golf", french: "golf"),
                EmojiWordModel(emoji: "🎿", italian: "lo sci", french: "ski")
            ]),
            EmojiCategoryModel(name: "Lieux", icon: "🏠", items: [
                EmojiWordModel(emoji: "🏠", italian: "la casa", french: "maison"),
                EmojiWordModel(emoji: "🏫", italian: "la scuola", french: "école"),
                EmojiWordModel(emoji: "🏥", italian: "l'ospedale", french: "hôpital"),
                EmojiWordModel(emoji: "🏪", italian: "il negozio", french: "magasin"),
                EmojiWordModel(emoji: "🏦", italian: "la banca", french: "banque"),
                EmojiWordModel(emoji: "⛪", italian: "la chiesa", french: "église"),
                EmojiWordModel(emoji: "🏰", italian: "il castello", french: "château"),
                EmojiWordModel(emoji: "🏖️", italian: "la spiaggia", french: "plage"),
                EmojiWordModel(emoji: "🎭", italian: "il teatro", french: "théâtre"),
                EmojiWordModel(emoji: "🎢", italian: "il parco divertimenti", french: "parc d'attractions"),
                EmojiWordModel(emoji: "🏛️", italian: "il museo", french: "musée"),
                EmojiWordModel(emoji: "🏨", italian: "l'albergo", french: "hôtel"),
                EmojiWordModel(emoji: "🏟️", italian: "lo stadio", french: "stade")
            ]),
            EmojiCategoryModel(name: "Corps", icon: "👁️", items: [
                EmojiWordModel(emoji: "👁️", italian: "l'occhio", french: "œil"),
                EmojiWordModel(emoji: "👂", italian: "l'orecchio", french: "oreille"),
                EmojiWordModel(emoji: "👃", italian: "il naso", french: "nez"),
                EmojiWordModel(emoji: "👄", italian: "la bocca", french: "bouche"),
                EmojiWordModel(emoji: "🦷", italian: "il dente", french: "dent"),
                EmojiWordModel(emoji: "👅", italian: "la lingua", french: "langue"),
                EmojiWordModel(emoji: "✋", italian: "la mano", french: "main"),
                EmojiWordModel(emoji: "🦶", italian: "il piede", french: "pied"),
                EmojiWordModel(emoji: "❤️", italian: "il cuore", french: "cœur"),
                EmojiWordModel(emoji: "🧠", italian: "il cervello", french: "cerveau"),
                EmojiWordModel(emoji: "🦴", italian: "l'osso", french: "os"),
                EmojiWordModel(emoji: "💪", italian: "il muscolo", french: "muscle")
            ]),
            EmojiCategoryModel(name: "Métiers", icon: "👨‍⚕️", items: [
                EmojiWordModel(emoji: "👨‍⚕️", italian: "il medico", french: "médecin"),
                EmojiWordModel(emoji: "👨‍🏫", italian: "il professore", french: "professeur"),
                EmojiWordModel(emoji: "👨‍🍳", italian: "il cuoco", french: "cuisinier"),
                EmojiWordModel(emoji: "👨‍🚒", italian: "il pompiere", french: "pompier"),
                EmojiWordModel(emoji: "👮", italian: "il poliziotto", french: "policier"),
                EmojiWordModel(emoji: "👨‍🌾", italian: "l'agricoltore", french: "agriculteur"),
                EmojiWordModel(emoji: "👨‍🔧", italian: "il meccanico", french: "mécanicien"),
                EmojiWordModel(emoji: "👨‍💼", italian: "l'uomo d'affari", french: "homme d'affaires"),
                EmojiWordModel(emoji: "👨‍⚖️", italian: "il giudice", french: "juge"),
                EmojiWordModel(emoji: "👨‍🎨", italian: "l'artista", french: "artiste"),
                EmojiWordModel(emoji: "👨‍✈️", italian: "il pilota", french: "pilote")
            ]),
            EmojiCategoryModel(name: "Temps", icon: "⏰", items: [
                EmojiWordModel(emoji: "⏰", italian: "l'ora", french: "heure"),
                EmojiWordModel(emoji: "📅", italian: "il giorno", french: "jour"),
                EmojiWordModel(emoji: "🌅", italian: "la mattina", french: "matin"),
                EmojiWordModel(emoji: "🌇", italian: "la sera", french: "soir"),
                EmojiWordModel(emoji: "🌃", italian: "la notte", french: "nuit"),
                EmojiWordModel(emoji: "📆", italian: "la settimana", french: "semaine"),
                EmojiWordModel(emoji: "🗓️", italian: "il mese", french: "mois"),
                EmojiWordModel(emoji: "🎆", italian: "l'anno", french: "année"),
                EmojiWordModel(emoji: "⏱️", italian: "il cronometro", french: "chronomètre"),
                EmojiWordModel(emoji: "⌛", italian: "la clessidra", french: "sablier")
            ]),
            EmojiCategoryModel(name: "Actions", icon: "🏃", items: [
                EmojiWordModel(emoji: "🚶", italian: "camminare", french: "marcher"),
                EmojiWordModel(emoji: "🏃", italian: "correre", french: "courir"),
                EmojiWordModel(emoji: "🏊", italian: "nuotare", french: "nager"),
                EmojiWordModel(emoji: "💤", italian: "dormire", french: "dormir"),
                EmojiWordModel(emoji: "🍽️", italian: "mangiare", french: "manger"),
                EmojiWordModel(emoji: "🥤", italian: "bere", french: "boire"),
                EmojiWordModel(emoji: "📖", italian: "leggere", french: "lire"),
                EmojiWordModel(emoji: "✍️", italian: "scrivere", french: "écrire"),
                EmojiWordModel(emoji: "🎤", italian: "cantare", french: "chanter"),
                EmojiWordModel(emoji: "💃", italian: "ballare", french: "danser"),
                EmojiWordModel(emoji: "👏", italian: "applaudire", french: "applaudir"),
                EmojiWordModel(emoji: "🧹", italian: "pulire", french: "nettoyer"),
                EmojiWordModel(emoji: "🧺", italian: "fare il bucato", french: "faire la lessive"),
                EmojiWordModel(emoji: "🛌", italian: "andare a letto", french: "se coucher"),
                EmojiWordModel(emoji: "🚿", italian: "farsi la doccia", french: "se doucher")
            ]),
            EmojiCategoryModel(name: "Vêtements", icon: "👕", items: [
                EmojiWordModel(emoji: "👕", italian: "la maglietta", french: "t-shirt"),
                EmojiWordModel(emoji: "👖", italian: "i pantaloni", french: "pantalon"),
                EmojiWordModel(emoji: "👗", italian: "il vestito", french: "robe"),
                EmojiWordModel(emoji: "🧥", italian: "il cappotto", french: "manteau"),
                EmojiWordModel(emoji: "🧢", italian: "il cappello", french: "casquette"),
                EmojiWordModel(emoji: "👟", italian: "le scarpe", french: "chaussures"),
                EmojiWordModel(emoji: "🧦", italian: "i calzini", french: "chaussettes"),
                EmojiWordModel(emoji: "👔", italian: "la cravatta", french: "cravate"),
                EmojiWordModel(emoji: "👠", italian: "i tacchi", french: "talons"),
                EmojiWordModel(emoji: "👜", italian: "la borsetta", french: "sac à main")
            ]),
            EmojiCategoryModel(name: "Couleurs", icon: "🎨", items: [
                EmojiWordModel(emoji: "🔴", italian: "rosso", french: "rouge"),
                EmojiWordModel(emoji: "🔵", italian: "blu", french: "bleu"),
                EmojiWordModel(emoji: "🟢", italian: "verde", french: "vert"),
                EmojiWordModel(emoji: "🟡", italian: "giallo", french: "jaune"),
                EmojiWordModel(emoji: "⚫", italian: "nero", french: "noir"),
                EmojiWordModel(emoji: "⚪", italian: "bianco", french: "blanc"),
                EmojiWordModel(emoji: "🟠", italian: "arancione", french: "orange"),
                EmojiWordModel(emoji: "🌸", italian: "rosa", french: "rose"),
                EmojiWordModel(emoji: "🟣", italian: "viola", french: "violet"),
                EmojiWordModel(emoji: "🟤", italian: "marrone", french: "marron")
            ]),
            EmojiCategoryModel(name: "Famille", icon: "👨‍👩‍👧‍👦", items: [
                EmojiWordModel(emoji: "👩", italian: "la mamma", french: "mère"),
                EmojiWordModel(emoji: "👨", italian: "il papà", french: "père"),
                EmojiWordModel(emoji: "👦", italian: "il figlio", french: "fils"),
                EmojiWordModel(emoji: "👧", italian: "la figlia", french: "fille"),
                EmojiWordModel(emoji: "🧒", italian: "il bambino", french: "enfant"),
                EmojiWordModel(emoji: "👵", italian: "la nonna", french: "grand-mère"),
                EmojiWordModel(emoji: "👴", italian: "il nonno", french: "grand-père"),
                EmojiWordModel(emoji: "👨‍👩‍👧‍👦", italian: "la famiglia", french: "famille"),
                EmojiWordModel(emoji: "👶", italian: "il bebè", french: "bébé"),
                EmojiWordModel(emoji: "🧑", italian: "la persona", french: "personne")
            ]),
            EmojiCategoryModel(name: "Maison", icon: "🏡", items: [
                EmojiWordModel(emoji: "🏡", italian: "la casa", french: "maison"),
                EmojiWordModel(emoji: "🛏️", italian: "il letto", french: "lit"),
                EmojiWordModel(emoji: "🚿", italian: "la doccia", french: "douche"),
                EmojiWordModel(emoji: "🚪", italian: "la porta", french: "porte"),
                EmojiWordModel(emoji: "🪑", italian: "la sedia", french: "chaise"),
                EmojiWordModel(emoji: "🪟", italian: "la finestra", french: "fenêtre"),
                EmojiWordModel(emoji: "🧽", italian: "la spugna", french: "éponge"),
                EmojiWordModel(emoji: "🛋️", italian: "il divano", french: "canapé"),
                EmojiWordModel(emoji: "🍽️", italian: "il tavolo", french: "table"),
                EmojiWordModel(emoji: "🚽", italian: "il bagno", french: "toilettes")
            ]),
            EmojiCategoryModel(name: "École", icon: "🎓", items: [
                EmojiWordModel(emoji: "🎓", italian: "la scuola", french: "école"),
                EmojiWordModel(emoji: "🎒", italian: "lo zaino", french: "sac à dos"),
                EmojiWordModel(emoji: "📚", italian: "i libri", french: "livres"),
                EmojiWordModel(emoji: "✏️", italian: "la matita", french: "crayon"),
                EmojiWordModel(emoji: "🖊️", italian: "la penna", french: "stylo"),
                EmojiWordModel(emoji: "🧮", italian: "la calcolatrice", french: "calculatrice"),
                EmojiWordModel(emoji: "🧑‍🏫", italian: "l'insegnante", french: "professeur"),
                EmojiWordModel(emoji: "📐", italian: "il righello", french: "règle"),
                EmojiWordModel(emoji: "✂️", italian: "le forbici", french: "ciseaux"),
                EmojiWordModel(emoji: "📝", italian: "l'appunto", french: "note")
            ]),
            EmojiCategoryModel(name: "Ville", icon: "🏙️", items: [
                EmojiWordModel(emoji: "🏙️", italian: "la città", french: "ville"),
                EmojiWordModel(emoji: "🏬", italian: "il centro commerciale", french: "centre commercial"),
                EmojiWordModel(emoji: "🚇", italian: "la metropolitana", french: "métro"),
                EmojiWordModel(emoji: "🏢", italian: "l'ufficio", french: "immeuble"),
                EmojiWordModel(emoji: "🌉", italian: "il ponte", french: "pont"),
                EmojiWordModel(emoji: "🚦", italian: "il semaforo", french: "feu rouge"),
                EmojiWordModel(emoji: "🏩", italian: "il motel", french: "love hotel"),
                EmojiWordModel(emoji: "🚏", italian: "la fermata", french: "arrêt de bus")
            ]),
            EmojiCategoryModel(name: "Loisirs", icon: "🧸", items: [
                EmojiWordModel(emoji: "🎮", italian: "il videogioco", french: "jeu vidéo"),
                EmojiWordModel(emoji: "🎨", italian: "il disegno", french: "dessin"),
                EmojiWordModel(emoji: "🎧", italian: "la musica", french: "musique"),
                EmojiWordModel(emoji: "🎬", italian: "il film", french: "film"),
                EmojiWordModel(emoji: "📺", italian: "la serie", french: "série"),
                EmojiWordModel(emoji: "🧸", italian: "il giocattolo", french: "jouet"),
                EmojiWordModel(emoji: "🎪", italian: "il circo", french: "cirque"),
                EmojiWordModel(emoji: "🎯", italian: "le freccette", french: "fléchettes"),
                EmojiWordModel(emoji: "🎲", italian: "i dadi", french: "dés")
            ]),
            EmojiCategoryModel(name: "Technologie", icon: "💾", items: [
                EmojiWordModel(emoji: "💾", italian: "il disco", french: "disque"),
                EmojiWordModel(emoji: "🖥️", italian: "il computer fisso", french: "ordinateur fixe"),
                EmojiWordModel(emoji: "⌨️", italian: "la tastiera", french: "clavier"),
                EmojiWordModel(emoji: "🖱️", italian: "il mouse", french: "souris"),
                EmojiWordModel(emoji: "📱", italian: "lo smartphone", french: "smartphone"),
                EmojiWordModel(emoji: "📶", italian: "il wifi", french: "wifi"),
                EmojiWordModel(emoji: "🔌", italian: "la presa", french: "prise"),
                EmojiWordModel(emoji: "🔋", italian: "la batteria", french: "batterie"),
                EmojiWordModel(emoji: "💿", italian: "il CD", french: "CD")
            ]),
            EmojiCategoryModel(name: "Météo", icon: "🌤️", items: [
                EmojiWordModel(emoji: "☀️", italian: "soleggiato", french: "ensoleillé"),
                EmojiWordModel(emoji: "⛅", italian: "nuvoloso", french: "nuageux"),
                EmojiWordModel(emoji: "🌧️", italian: "piovoso", french: "pluvieux"),
                EmojiWordModel(emoji: "⛈️", italian: "temporalesco", french: "orageux"),
                EmojiWordModel(emoji: "🌨️", italian: "nevoso", french: "neigeux"),
                EmojiWordModel(emoji: "🌬️", italian: "ventoso", french: "venteux"),
                EmojiWordModel(emoji: "🌫️", italian: "nebbioso", french: "brumeux"),
                EmojiWordModel(emoji: "🌡️", italian: "la temperatura", french: "température")
            ]),
            EmojiCategoryModel(name: "Fêtes", icon: "🎉", items: [
                EmojiWordModel(emoji: "🎉", italian: "la festa", french: "fête"),
                EmojiWordModel(emoji: "🎂", italian: "il compleanno", french: "anniversaire"),
                EmojiWordModel(emoji: "🎄", italian: "Natale", french: "Noël"),
                EmojiWordModel(emoji: "🎃", italian: "Halloween", french: "Halloween"),
                EmojiWordModel(emoji: "🎆", italian: "i fuochi d'artificio", french: "feu d'artifice"),
                EmojiWordModel(emoji: "🎊", italian: "i coriandoli", french: "confettis"),
                EmojiWordModel(emoji: "🎁", italian: "il regalo", french: "cadeau"),
                EmojiWordModel(emoji: "🎈", italian: "il palloncino", french: "ballon")
            ]),
            EmojiCategoryModel(name: "Nombres", icon: "🔢", items: [
                EmojiWordModel(emoji: "0️⃣", italian: "zero", french: "zéro"),
                EmojiWordModel(emoji: "1️⃣", italian: "uno", french: "un"),
                EmojiWordModel(emoji: "2️⃣", italian: "due", french: "deux"),
                EmojiWordModel(emoji: "3️⃣", italian: "tre", french: "trois"),
                EmojiWordModel(emoji: "4️⃣", italian: "quattro", french: "quatre"),
                EmojiWordModel(emoji: "5️⃣", italian: "cinque", french: "cinq"),
                EmojiWordModel(emoji: "6️⃣", italian: "sei", french: "six"),
                EmojiWordModel(emoji: "7️⃣", italian: "sette", french: "sept"),
                EmojiWordModel(emoji: "8️⃣", italian: "otto", french: "huit"),
                EmojiWordModel(emoji: "9️⃣", italian: "nove", french: "neuf"),
                EmojiWordModel(emoji: "🔟", italian: "dieci", french: "dix"),
                EmojiWordModel(emoji: "💯", italian: "cento", french: "cent"),
                EmojiWordModel(emoji: "🔢", italian: "il numero", french: "nombre"),
                EmojiWordModel(emoji: "➕", italian: "più", french: "plus"),
                EmojiWordModel(emoji: "➖", italian: "meno", french: "moins")
            ]),
            EmojiCategoryModel(name: "Calendrier", icon: "📆", items: [
                EmojiWordModel(emoji: "📆", italian: "lunedì", french: "lundi"),
                EmojiWordModel(emoji: "📅", italian: "martedì", french: "mardi"),
                EmojiWordModel(emoji: "🗓️", italian: "mercoledì", french: "mercredi"),
                EmojiWordModel(emoji: "📋", italian: "giovedì", french: "jeudi"),
                EmojiWordModel(emoji: "📃", italian: "venerdì", french: "vendredi"),
                EmojiWordModel(emoji: "📄", italian: "sabato", french: "samedi"),
                EmojiWordModel(emoji: "🗒️", italian: "domenica", french: "dimanche"),
                EmojiWordModel(emoji: "🌸", italian: "la primavera", french: "printemps"),
                EmojiWordModel(emoji: "☀️", italian: "l'estate", french: "été"),
                EmojiWordModel(emoji: "🍂", italian: "l'autunno", french: "automne"),
                EmojiWordModel(emoji: "❄️", italian: "l'inverno", french: "hiver"),
                EmojiWordModel(emoji: "🌷", italian: "marzo", french: "mars"),
                EmojiWordModel(emoji: "🌼", italian: "aprile", french: "avril"),
                EmojiWordModel(emoji: "🌺", italian: "maggio", french: "mai"),
                EmojiWordModel(emoji: "🌻", italian: "giugno", french: "juin")
            ]),
            EmojiCategoryModel(name: "Sentiments", icon: "💖", items: [
                EmojiWordModel(emoji: "❤️", italian: "l'amore", french: "amour"),
                EmojiWordModel(emoji: "💔", italian: "il cuore spezzato", french: "cœur brisé"),
                EmojiWordModel(emoji: "💖", italian: "l'affetto", french: "affection"),
                EmojiWordModel(emoji: "😊", italian: "la gioia", french: "joie"),
                EmojiWordModel(emoji: "😢", italian: "la tristezza", french: "tristesse"),
                EmojiWordModel(emoji: "😰", italian: "la paura", french: "peur"),
                EmojiWordModel(emoji: "😡", italian: "la rabbia", french: "colère"),
                EmojiWordModel(emoji: "😌", italian: "la pace", french: "paix"),
                EmojiWordModel(emoji: "🤗", italian: "la tenerezza", french: "tendresse"),
                EmojiWordModel(emoji: "😳", italian: "la sorpresa", french: "surprise"),
                EmojiWordModel(emoji: "😔", italian: "la delusione", french: "déception"),
                EmojiWordModel(emoji: "🥰", italian: "la felicità", french: "bonheur"),
                EmojiWordModel(emoji: "😤", italian: "la gelosia", french: "jalousie"),
                EmojiWordModel(emoji: "😨", italian: "l'ansia", french: "anxiété")
            ]),
            EmojiCategoryModel(name: "Adjectifs Utiles", icon: "⭐", items: [
                EmojiWordModel(emoji: "😀", italian: "felice", french: "heureux"),
                EmojiWordModel(emoji: "😢", italian: "triste", french: "triste"),
                EmojiWordModel(emoji: "💪", italian: "forte", french: "fort"),
                EmojiWordModel(emoji: "🤏", italian: "piccolo", french: "petit"),
                EmojiWordModel(emoji: "🏔️", italian: "grande", french: "grand"),
                EmojiWordModel(emoji: "🔥", italian: "caldo", french: "chaud"),
                EmojiWordModel(emoji: "❄️", italian: "freddo", french: "froid"),
                EmojiWordModel(emoji: "✨", italian: "bello", french: "beau"),
                EmojiWordModel(emoji: "👎", italian: "cattivo", french: "mauvais"),
                EmojiWordModel(emoji: "👍", italian: "buono", french: "bon"),
                EmojiWordModel(emoji: "🐌", italian: "lento", french: "lent"),
                EmojiWordModel(emoji: "🚀", italian: "veloce", french: "rapide"),
                EmojiWordModel(emoji: "😴", italian: "stanco", french: "fatigué"),
                EmojiWordModel(emoji: "⚡", italian: "energico", french: "énergique"),
                EmojiWordModel(emoji: "🔊", italian: "rumoroso", french: "bruyant"),
                EmojiWordModel(emoji: "🔇", italian: "silenzioso", french: "silencieux"),
                EmojiWordModel(emoji: "💰", italian: "ricco", french: "riche"),
                EmojiWordModel(emoji: "💸", italian: "povero", french: "pauvre"),
                EmojiWordModel(emoji: "🧠", italian: "intelligente", french: "intelligent"),
                EmojiWordModel(emoji: "😵", italian: "confuso", french: "confus")
            ]),
            EmojiCategoryModel(name: "Verbes Essentiels", icon: "🎬", items: [
                EmojiWordModel(emoji: "👋", italian: "salutare", french: "saluer"),
                EmojiWordModel(emoji: "🗣️", italian: "parlare", french: "parler"),
                EmojiWordModel(emoji: "👂", italian: "ascoltare", french: "écouter"),
                EmojiWordModel(emoji: "👀", italian: "guardare", french: "regarder"),
                EmojiWordModel(emoji: "🤝", italian: "dare", french: "donner"),
                EmojiWordModel(emoji: "✋", italian: "prendere", french: "prendre"),
                EmojiWordModel(emoji: "🚶", italian: "andare", french: "aller"),
                EmojiWordModel(emoji: "🔙", italian: "venire", french: "venir"),
                EmojiWordModel(emoji: "💭", italian: "pensare", french: "penser"),
                EmojiWordModel(emoji: "🧠", italian: "capire", french: "comprendre"),
                EmojiWordModel(emoji: "❤️", italian: "amare", french: "aimer"),
                EmojiWordModel(emoji: "💔", italian: "odiare", french: "détester"),
                EmojiWordModel(emoji: "🙏", italian: "chiedere", french: "demander"),
                EmojiWordModel(emoji: "💬", italian: "rispondere", french: "répondre"),
                EmojiWordModel(emoji: "🎓", italian: "imparare", french: "apprendre"),
                EmojiWordModel(emoji: "📖", italian: "studiare", french: "étudier"),
                EmojiWordModel(emoji: "💼", italian: "lavorare", french: "travailler"),
                EmojiWordModel(emoji: "😴", italian: "riposare", french: "se reposer")
            ]),
            EmojiCategoryModel(name: "Expressions Courantes", icon: "💬", items: [
                EmojiWordModel(emoji: "👋", italian: "ciao", french: "bonjour"),
                EmojiWordModel(emoji: "🌅", italian: "buongiorno", french: "bonjour (matin)"),
                EmojiWordModel(emoji: "🌆", italian: "buonasera", french: "bonsoir"),
                EmojiWordModel(emoji: "🌙", italian: "buonanotte", french: "bonne nuit"),
                EmojiWordModel(emoji: "👋", italian: "arrivederci", french: "au revoir"),
                EmojiWordModel(emoji: "🙏", italian: "per favore", french: "s'il vous plaît"),
                EmojiWordModel(emoji: "❤️", italian: "grazie", french: "merci"),
                EmojiWordModel(emoji: "👍", italian: "prego", french: "de rien"),
                EmojiWordModel(emoji: "😔", italian: "scusa", french: "pardon"),
                EmojiWordModel(emoji: "❓", italian: "come stai?", french: "comment ça va?"),
                EmojiWordModel(emoji: "👍", italian: "bene", french: "bien"),
                EmojiWordModel(emoji: "👎", italian: "male", french: "mal"),
                EmojiWordModel(emoji: "❔", italian: "perché?", french: "pourquoi?"),
                EmojiWordModel(emoji: "📍", italian: "dove?", french: "où?"),
                EmojiWordModel(emoji: "⏰", italian: "quando?", french: "quand?"),
                EmojiWordModel(emoji: "👤", italian: "chi?", french: "qui?"),
                EmojiWordModel(emoji: "🤔", italian: "cosa?", french: "quoi?"),
                EmojiWordModel(emoji: "✅", italian: "sì", french: "oui"),
                EmojiWordModel(emoji: "❌", italian: "no", french: "non"),
                EmojiWordModel(emoji: "🤷", italian: "forse", french: "peut-être")
            ]),
            EmojiCategoryModel(name: "Cuisine", icon: "🍳", items: [
                EmojiWordModel(emoji: "🍳", italian: "la colazione", french: "petit-déjeuner"),
                EmojiWordModel(emoji: "🍽️", italian: "il pranzo", french: "déjeuner"),
                EmojiWordModel(emoji: "🌙", italian: "la cena", french: "dîner"),
                EmojiWordModel(emoji: "🥄", italian: "il cucchiaio", french: "cuillère"),
                EmojiWordModel(emoji: "🍴", italian: "la forchetta", french: "fourchette"),
                EmojiWordModel(emoji: "🔪", italian: "il coltello", french: "couteau"),
                EmojiWordModel(emoji: "🍽️", italian: "il piatto", french: "assiette"),
                EmojiWordModel(emoji: "🥛", italian: "il bicchiere", french: "verre"),
                EmojiWordModel(emoji: "☕", italian: "la tazza", french: "tasse"),
                EmojiWordModel(emoji: "🍳", italian: "cucinare", french: "cuisiner"),
                EmojiWordModel(emoji: "🔥", italian: "bollire", french: "bouillir"),
                EmojiWordModel(emoji: "🍞", italian: "grigliare", french: "griller"),
                EmojiWordModel(emoji: "🧂", italian: "il sale", french: "sel"),
                EmojiWordModel(emoji: "🌶️", italian: "il pepe", french: "poivre"),
                EmojiWordModel(emoji: "🍯", italian: "lo zucchero", french: "sucre"),
                EmojiWordModel(emoji: "🧈", italian: "il burro", french: "beurre"),
                EmojiWordModel(emoji: "🥛", italian: "il latte", french: "lait"),
                EmojiWordModel(emoji: "💧", italian: "l'acqua", french: "eau")
            ]),
            EmojiCategoryModel(name: "Santé", icon: "🏥", items: [
                EmojiWordModel(emoji: "🏥", italian: "l'ospedale", french: "hôpital"),
                EmojiWordModel(emoji: "💊", italian: "la medicina", french: "médicament"),
                EmojiWordModel(emoji: "💉", italian: "l'iniezione", french: "injection"),
                EmojiWordModel(emoji: "🩹", italian: "il cerotto", french: "pansement"),
                EmojiWordModel(emoji: "🌡️", italian: "il termometro", french: "thermomètre"),
                EmojiWordModel(emoji: "🩺", italian: "lo stetoscopio", french: "stéthoscope"),
                EmojiWordModel(emoji: "🦷", italian: "il dentista", french: "dentiste"),
                EmojiWordModel(emoji: "🧴", italian: "la crema", french: "crème"),
                EmojiWordModel(emoji: "🧼", italian: "il sapone", french: "savon"),
                EmojiWordModel(emoji: "🪥", italian: "lo spazzolino", french: "brosse à dents"),
                EmojiWordModel(emoji: "💪", italian: "la salute", french: "santé")
            ]),
            EmojiCategoryModel(name: "Voyage", icon: "✈️", items: [
                EmojiWordModel(emoji: "✈️", italian: "il viaggio", french: "voyage"),
                EmojiWordModel(emoji: "🧳", italian: "la valigia", french: "valise"),
                EmojiWordModel(emoji: "🎫", italian: "il biglietto", french: "billet"),
                EmojiWordModel(emoji: "🗺️", italian: "la mappa", french: "carte"),
                EmojiWordModel(emoji: "📍", italian: "la destinazione", french: "destination"),
                EmojiWordModel(emoji: "🏨", italian: "l'albergo", french: "hôtel"),
                EmojiWordModel(emoji: "🏖️", italian: "le vacanze", french: "vacances"),
                EmojiWordModel(emoji: "📸", italian: "la foto", french: "photo"),
                EmojiWordModel(emoji: "🧭", italian: "la bussola", french: "boussole"),
                EmojiWordModel(emoji: "🗼", italian: "il monumento", french: "monument"),
                EmojiWordModel(emoji: "🛂", italian: "il passaporto", french: "passeport")
            ]),
            EmojiCategoryModel(name: "Argent", icon: "💰", items: [
                EmojiWordModel(emoji: "💰", italian: "i soldi", french: "argent"),
                EmojiWordModel(emoji: "💵", italian: "la banconota", french: "billet"),
                EmojiWordModel(emoji: "💳", italian: "la carta di credito", french: "carte bancaire"),
                EmojiWordModel(emoji: "🏦", italian: "la banca", french: "banque"),
                EmojiWordModel(emoji: "💸", italian: "spendere", french: "dépenser"),
                EmojiWordModel(emoji: "💲", italian: "il prezzo", french: "prix"),
                EmojiWordModel(emoji: "🛒", italian: "il carrello", french: "caddie"),
                EmojiWordModel(emoji: "🛍️", italian: "lo shopping", french: "shopping"),
                EmojiWordModel(emoji: "🏪", italian: "il negozio", french: "boutique"),
                EmojiWordModel(emoji: "💎", italian: "costoso", french: "cher")
            ]),
            EmojiCategoryModel(name: "Communication", icon: "📱", items: [
                EmojiWordModel(emoji: "📱", italian: "chiamare", french: "appeler"),
                EmojiWordModel(emoji: "💬", italian: "il messaggio", french: "message"),
                EmojiWordModel(emoji: "📧", italian: "l'email", french: "email"),
                EmojiWordModel(emoji: "📬", italian: "la posta", french: "courrier"),
                EmojiWordModel(emoji: "📞", italian: "il telefono", french: "téléphone"),
                EmojiWordModel(emoji: "🔔", italian: "la notifica", french: "notification"),
                EmojiWordModel(emoji: "🗣️", italian: "discutere", french: "discuter"),
                EmojiWordModel(emoji: "💭", italian: "pensare", french: "penser"),
                EmojiWordModel(emoji: "📝", italian: "scrivere", french: "écrire")
            ]),
            EmojiCategoryModel(name: "Géographie", icon: "🌍", items: [
                EmojiWordModel(emoji: "🌍", italian: "il mondo", french: "monde"),
                EmojiWordModel(emoji: "🗺️", italian: "il continente", french: "continent"),
                EmojiWordModel(emoji: "🇮🇹", italian: "l'Italia", french: "Italie"),
                EmojiWordModel(emoji: "🇪🇸", italian: "la Spagna", french: "Espagne"),
                EmojiWordModel(emoji: "🇫🇷", italian: "la Francia", french: "France"),
                EmojiWordModel(emoji: "🏙️", italian: "la capitale", french: "capitale"),
                EmojiWordModel(emoji: "🗾", italian: "il paese", french: "pays"),
                EmojiWordModel(emoji: "🧳", italian: "viaggiare", french: "voyager")
            ]),
            EmojiCategoryModel(name: "Musique", icon: "🎵", items: [
                EmojiWordModel(emoji: "🎵", italian: "la musica", french: "musique"),
                EmojiWordModel(emoji: "🎶", italian: "la canzone", french: "chanson"),
                EmojiWordModel(emoji: "🎤", italian: "il cantante", french: "chanteur"),
                EmojiWordModel(emoji: "🎸", italian: "la chitarra", french: "guitare"),
                EmojiWordModel(emoji: "🎹", italian: "il pianoforte", french: "piano"),
                EmojiWordModel(emoji: "🥁", italian: "la batteria", french: "batterie"),
                EmojiWordModel(emoji: "🎺", italian: "la tromba", french: "trompette"),
                EmojiWordModel(emoji: "🎻", italian: "il violino", french: "violon"),
                EmojiWordModel(emoji: "🎨", italian: "l'arte", french: "art"),
                EmojiWordModel(emoji: "🎭", italian: "il teatro", french: "théâtre"),
                EmojiWordModel(emoji: "🎬", italian: "il cinema", french: "cinéma")
            ])
        ]
    }
}
