devices([
  "iPhone 15 Pro",
  "iPhone 15 Pro Max",
  "iPhone SE (3rd generation)",
  "iPad Pro (12.9-inch) (6th generation)"
])

languages([
  "fr-FR",
  "it-IT",
  "en-US"
])

scheme("onykroua")

output_directory("./fastlane/screenshots")

clear_previous_screenshots(true)

override_status_bar(true)

number_of_retries(3)
