package com.loicberthod.onykroua.emoji

object EmojiData {
    
    fun getEmojiCategories(language: String): List<EmojiCategory> {
        return if (language == "it") getItalianEmojis() else getSpanishEmojis()
    }
    
    fun getEmojiStories(language: String): List<EmojiStory> {
        return if (language == "it") getItalianStories() else getSpanishStories()
    }
    
    private fun getItalianEmojis(): List<EmojiCategory> {
        return listOf(
            EmojiCategory("Émotions", "😊", listOf(
                EmojiWord("😀", "content", "contento"),
                EmojiWord("😢", "triste", "triste"),
                EmojiWord("😡", "en colère", "arrabbiato"),
                EmojiWord("😱", "effrayé", "spaventato"),
                EmojiWord("😍", "amoureux", "innamorato"),
                EmojiWord("🤔", "pensif", "pensieroso"),
                EmojiWord("😴", "fatigué", "stanco"),
                EmojiWord("🤢", "malade", "malato"),
                EmojiWord("😎", "cool", "figo"),
                EmojiWord("🥳", "festif", "festoso"),
                EmojiWord("😤", "frustré", "frustrato"),
                EmojiWord("🥺", "suppliant", "implorante"),
                EmojiWord("🤩", "impressionné", "impressionato"),
                EmojiWord("😭", "en larmes", "in lacrime"),
                EmojiWord("😇", "sage", "buono"),
                EmojiWord("🤗", "câlin", "abbraccio"),
                EmojiWord("😏", "malin", "furbo"),
                EmojiWord("🥱", "bâillant", "sbadigliante"),
                EmojiWord("😵", "étourdi", "stordito"),
                EmojiWord("🤪", "fou", "pazzo")
            )),
            EmojiCategory("Nourriture", "🍕", listOf(
                EmojiWord("🍕", "pizza", "la pizza"),
                EmojiWord("🍝", "pâtes", "la pasta"),
                EmojiWord("🍞", "pain", "il pane"),
                EmojiWord("🧀", "fromage", "il formaggio"),
                EmojiWord("🍷", "vin", "il vino"),
                EmojiWord("☕", "café", "il caffè"),
                EmojiWord("🍦", "glace", "il gelato"),
                EmojiWord("🍎", "pomme", "la mela"),
                EmojiWord("🍊", "orange", "l'arancia"),
                EmojiWord("🍋", "citron", "il limone"),
                EmojiWord("🍇", "raisin", "l'uva"),
                EmojiWord("🍓", "fraise", "la fragola"),
                EmojiWord("🥕", "carotte", "la carota"),
                EmojiWord("🥒", "concombre", "il cetriolo"),
                EmojiWord("🍅", "tomate", "il pomodoro"),
                EmojiWord("🥚", "œuf", "l'uovo"),
                EmojiWord("🍌", "banane", "la banana"),
                EmojiWord("🍰", "gâteau", "la torta"),
                EmojiWord("🍟", "frites", "le patatine"),
                EmojiWord("🍔", "hamburger", "l'hamburger"),
                EmojiWord("🌮", "taco", "il taco"),
                EmojiWord("🍿", "pop-corn", "i popcorn"),
                EmojiWord("🍩", "donut", "la ciambella"),
                EmojiWord("🍪", "cookie", "il biscotto"),
                EmojiWord("🥐", "croissant", "il cornetto")
            )),
            EmojiCategory("Animaux", "🐱", listOf(
                EmojiWord("🐱", "chat", "il gatto"),
                EmojiWord("🐶", "chien", "il cane"),
                EmojiWord("🐦", "oiseau", "l'uccello"),
                EmojiWord("🐟", "poisson", "il pesce"),
                EmojiWord("🐴", "cheval", "il cavallo"),
                EmojiWord("🐄", "vache", "la mucca"),
                EmojiWord("🐷", "cochon", "il maiale"),
                EmojiWord("🐑", "mouton", "la pecora"),
                EmojiWord("🐓", "coq", "il gallo"),
                EmojiWord("🦋", "papillon", "la farfalla"),
                EmojiWord("🐝", "abeille", "l'ape"),
                EmojiWord("🐢", "tortue", "la tartaruga"),
                EmojiWord("🐘", "éléphant", "l'elefante"),
                EmojiWord("🦁", "lion", "il leone"),
                EmojiWord("🐻", "ours", "l'orso"),
                EmojiWord("🐰", "lapin", "il coniglio"),
                EmojiWord("🦊", "renard", "la volpe"),
                EmojiWord("🐯", "tigre", "la tigre"),
                EmojiWord("🦒", "girafe", "la giraffa"),
                EmojiWord("🐼", "panda", "il panda"),
                EmojiWord("🐨", "koala", "il koala"),
                EmojiWord("🦘", "kangourou", "il canguro"),
                EmojiWord("🐸", "grenouille", "la rana"),
                EmojiWord("🐍", "serpent", "il serpente")
            )),
            EmojiCategory("Nature", "🌳", listOf(
                EmojiWord("🌳", "arbre", "l'albero"),
                EmojiWord("🌸", "fleur", "il fiore"),
                EmojiWord("🌞", "soleil", "il sole"),
                EmojiWord("🌙", "lune", "la luna"),
                EmojiWord("⭐", "étoile", "la stella"),
                EmojiWord("🌧️", "pluie", "la pioggia"),
                EmojiWord("❄️", "neige", "la neve"),
                EmojiWord("🌈", "arc-en-ciel", "l'arcobaleno"),
                EmojiWord("🌊", "vague", "l'onda"),
                EmojiWord("⛰️", "montagne", "la montagna"),
                EmojiWord("🏝️", "île", "l'isola"),
                EmojiWord("🌴", "palmier", "la palma"),
                EmojiWord("🌵", "cactus", "il cactus"),
                EmojiWord("🌺", "hibiscus", "l'ibisco"),
                EmojiWord("🌻", "tournesol", "il girasole"),
                EmojiWord("🌹", "rose", "la rosa"),
                EmojiWord("🍀", "trèfle", "il trifoglio"),
                EmojiWord("🍁", "érable", "l'acero"),
                EmojiWord("🌾", "blé", "il grano")
            )),
            EmojiCategory("Transports", "🚗", listOf(
                EmojiWord("🚗", "voiture", "la macchina"),
                EmojiWord("🚌", "bus", "l'autobus"),
                EmojiWord("🚂", "train", "il treno"),
                EmojiWord("✈️", "avion", "l'aereo"),
                EmojiWord("🚢", "bateau", "la nave"),
                EmojiWord("🚲", "vélo", "la bicicletta"),
                EmojiWord("🏍️", "moto", "la moto"),
                EmojiWord("🚁", "hélicoptère", "l'elicottero"),
                EmojiWord("🚀", "fusée", "il razzo"),
                EmojiWord("🛴", "trottinette", "il monopattino"),
                EmojiWord("🚕", "taxi", "il taxi"),
                EmojiWord("🚙", "SUV", "il SUV"),
                EmojiWord("🚎", "trolleybus", "il filobus")
            )),
            EmojiCategory("Objets", "📱", listOf(
                EmojiWord("📱", "téléphone", "il telefono"),
                EmojiWord("💻", "ordinateur", "il computer"),
                EmojiWord("📺", "télévision", "la televisione"),
                EmojiWord("📷", "appareil photo", "la macchina fotografica"),
                EmojiWord("🎸", "guitare", "la chitarra"),
                EmojiWord("🎹", "piano", "il pianoforte"),
                EmojiWord("📚", "livres", "i libri"),
                EmojiWord("✏️", "crayon", "la matita"),
                EmojiWord("🔑", "clé", "la chiave"),
                EmojiWord("💡", "ampoule", "la lampadina"),
                EmojiWord("🕶️", "lunettes", "gli occhiali"),
                EmojiWord("👜", "sac", "la borsa"),
                EmojiWord("⌚", "montre", "l'orologio"),
                EmojiWord("💍", "bague", "l'anello"),
                EmojiWord("👑", "couronne", "la corona"),
                EmojiWord("🎁", "cadeau", "il regalo"),
                EmojiWord("🎈", "ballon", "il palloncino"),
                EmojiWord("🔦", "lampe", "la torcia")
            )),
            EmojiCategory("Sports", "⚽", listOf(
                EmojiWord("⚽", "football", "il calcio"),
                EmojiWord("🏀", "basketball", "la pallacanestro"),
                EmojiWord("🎾", "tennis", "il tennis"),
                EmojiWord("🏊", "natation", "il nuoto"),
                EmojiWord("🚴", "cyclisme", "il ciclismo"),
                EmojiWord("⛷️", "ski", "lo sci"),
                EmojiWord("🏃", "course", "la corsa"),
                EmojiWord("🥊", "boxe", "la boxe"),
                EmojiWord("🏐", "volleyball", "la pallavolo"),
                EmojiWord("🏈", "football américain", "il football americano"),
                EmojiWord("⛳", "golf", "il golf"),
                EmojiWord("🎿", "ski", "lo sci")
            )),
            EmojiCategory("Lieux", "🏠", listOf(
                EmojiWord("🏠", "maison", "la casa"),
                EmojiWord("🏫", "école", "la scuola"),
                EmojiWord("🏥", "hôpital", "l'ospedale"),
                EmojiWord("🏪", "magasin", "il negozio"),
                EmojiWord("🏦", "banque", "la banca"),
                EmojiWord("⛪", "église", "la chiesa"),
                EmojiWord("🏰", "château", "il castello"),
                EmojiWord("🏖️", "plage", "la spiaggia"),
                EmojiWord("🎭", "théâtre", "il teatro"),
                EmojiWord("🎢", "parc d'attractions", "il parco divertimenti"),
                EmojiWord("🏛️", "musée", "il museo"),
                EmojiWord("🏨", "hôtel", "l'albergo"),
                EmojiWord("🏟️", "stade", "lo stadio")
            )),
            EmojiCategory("Corps", "👁️", listOf(
                EmojiWord("👁️", "œil", "l'occhio"),
                EmojiWord("👂", "oreille", "l'orecchio"),
                EmojiWord("👃", "nez", "il naso"),
                EmojiWord("👄", "bouche", "la bocca"),
                EmojiWord("🦷", "dent", "il dente"),
                EmojiWord("👅", "langue", "la lingua"),
                EmojiWord("✋", "main", "la mano"),
                EmojiWord("🦶", "pied", "il piede"),
                EmojiWord("❤️", "cœur", "il cuore"),
                EmojiWord("🧠", "cerveau", "il cervello"),
                EmojiWord("🦴", "os", "l'osso"),
                EmojiWord("💪", "muscle", "il muscolo")
            )),
            EmojiCategory("Métiers", "👨‍⚕️", listOf(
                EmojiWord("👨‍⚕️", "médecin", "il medico"),
                EmojiWord("👨‍🏫", "professeur", "il professore"),
                EmojiWord("👨‍🍳", "cuisinier", "il cuoco"),
                EmojiWord("👨‍🚒", "pompier", "il pompiere"),
                EmojiWord("👮", "policier", "il poliziotto"),
                EmojiWord("👨‍🌾", "agriculteur", "l'agricoltore"),
                EmojiWord("👨‍🔧", "mécanicien", "il meccanico"),
                EmojiWord("👨‍💼", "homme d'affaires", "l'uomo d'affari"),
                EmojiWord("👨‍⚖️", "juge", "il giudice"),
                EmojiWord("👨‍🎨", "artiste", "l'artista"),
                EmojiWord("👨‍✈️", "pilote", "il pilota")
            )),
            EmojiCategory("Temps", "⏰", listOf(
                EmojiWord("⏰", "heure", "l'ora"),
                EmojiWord("📅", "jour", "il giorno"),
                EmojiWord("🌅", "matin", "la mattina"),
                EmojiWord("🌇", "soir", "la sera"),
                EmojiWord("🌃", "nuit", "la notte"),
                EmojiWord("📆", "semaine", "la settimana"),
                EmojiWord("🗓️", "mois", "il mese"),
                EmojiWord("🎆", "année", "l'anno"),
                EmojiWord("⏱️", "chronomètre", "il cronometro"),
                EmojiWord("⌛", "sablier", "la clessidra")
            )),
            EmojiCategory("Actions", "🏃", listOf(
                EmojiWord("🚶", "marcher", "camminare"),
                EmojiWord("🏃", "courir", "correre"),
                EmojiWord("🏊", "nager", "nuotare"),
                EmojiWord("💤", "dormir", "dormire"),
                EmojiWord("🍽️", "manger", "mangiare"),
                EmojiWord("🥤", "boire", "bere"),
                EmojiWord("📖", "lire", "leggere"),
                EmojiWord("✍️", "écrire", "scrivere"),
                EmojiWord("🎤", "chanter", "cantare"),
                EmojiWord("💃", "danser", "ballare"),
                EmojiWord("👏", "applaudir", "applaudire"),
                EmojiWord("🧹", "nettoyer", "pulire"),
                EmojiWord("🧺", "faire la lessive", "fare il bucato"),
                EmojiWord("🛌", "se coucher", "andare a letto"),
                EmojiWord("🚿", "se doucher", "farsi la doccia")
            )),
            EmojiCategory("Vêtements", "👕", listOf(
                EmojiWord("👕", "t-shirt", "la maglietta"),
                EmojiWord("👖", "pantalon", "i pantaloni"),
                EmojiWord("👗", "robe", "il vestito"),
                EmojiWord("🧥", "manteau", "il cappotto"),
                EmojiWord("🧢", "casquette", "il cappello"),
                EmojiWord("👟", "chaussures", "le scarpe"),
                EmojiWord("🧦", "chaussettes", "i calzini"),
                EmojiWord("👔", "cravate", "la cravatta"),
                EmojiWord("👠", "talons", "i tacchi"),
                EmojiWord("👜", "sac à main", "la borsetta")
            )),
            EmojiCategory("Couleurs", "🎨", listOf(
                EmojiWord("🔴", "rouge", "rosso"),
                EmojiWord("🔵", "bleu", "blu"),
                EmojiWord("🟢", "vert", "verde"),
                EmojiWord("🟡", "jaune", "giallo"),
                EmojiWord("⚫", "noir", "nero"),
                EmojiWord("⚪", "blanc", "bianco"),
                EmojiWord("🟠", "orange", "arancione"),
                EmojiWord("🌸", "rose", "rosa"),
                EmojiWord("🟣", "violet", "viola"),
                EmojiWord("🟤", "marron", "marrone")
            )),
            EmojiCategory("Famille", "👨‍👩‍👧‍👦", listOf(
                EmojiWord("👩", "mère", "la mamma"),
                EmojiWord("👨", "père", "il papà"),
                EmojiWord("👦", "fils", "il figlio"),
                EmojiWord("👧", "fille", "la figlia"),
                EmojiWord("🧒", "enfant", "il bambino"),
                EmojiWord("👵", "grand-mère", "la nonna"),
                EmojiWord("👴", "grand-père", "il nonno"),
                EmojiWord("👨‍👩‍👧‍👦", "famille", "la famiglia"),
                EmojiWord("👶", "bébé", "il bebè"),
                EmojiWord("🧑", "personne", "la persona")
            )),
            EmojiCategory("Maison", "🏡", listOf(
                EmojiWord("🏡", "maison", "la casa"),
                EmojiWord("🛏️", "lit", "il letto"),
                EmojiWord("🚿", "douche", "la doccia"),
                EmojiWord("🚪", "porte", "la porta"),
                EmojiWord("🪑", "chaise", "la sedia"),
                EmojiWord("🪟", "fenêtre", "la finestra"),
                EmojiWord("🧽", "éponge", "la spugna"),
                EmojiWord("🛋️", "canapé", "il divano"),
                EmojiWord("🍽️", "table", "il tavolo"),
                EmojiWord("🚽", "toilettes", "il bagno")
            )),
            EmojiCategory("École", "🎓", listOf(
                EmojiWord("🎓", "école", "la scuola"),
                EmojiWord("🎒", "sac à dos", "lo zaino"),
                EmojiWord("📚", "livres", "i libri"),
                EmojiWord("✏️", "crayon", "la matita"),
                EmojiWord("🖊️", "stylo", "la penna"),
                EmojiWord("🧮", "calculatrice", "la calcolatrice"),
                EmojiWord("🧑‍🏫", "professeur", "l'insegnante"),
                EmojiWord("📐", "règle", "il righello"),
                EmojiWord("✂️", "ciseaux", "le forbici"),
                EmojiWord("📝", "note", "l'appunto")
            )),
            EmojiCategory("Ville", "🏙️", listOf(
                EmojiWord("🏙️", "ville", "la città"),
                EmojiWord("🏬", "centre commercial", "il centro commerciale"),
                EmojiWord("🚇", "métro", "la metropolitana"),
                EmojiWord("🏢", "immeuble", "l'ufficio"),
                EmojiWord("🌉", "pont", "il ponte"),
                EmojiWord("🚦", "feu rouge", "il semaforo"),
                EmojiWord("🏩", "love hotel", "il motel"),
                EmojiWord("🚏", "arrêt de bus", "la fermata")
            )),
            EmojiCategory("Loisirs", "🧸", listOf(
                EmojiWord("🎮", "jeu vidéo", "il videogioco"),
                EmojiWord("🎨", "dessin", "il disegno"),
                EmojiWord("🎧", "musique", "la musica"),
                EmojiWord("🎬", "film", "il film"),
                EmojiWord("📺", "série", "la serie"),
                EmojiWord("🧸", "jouet", "il giocattolo"),
                EmojiWord("🎪", "cirque", "il circo"),
                EmojiWord("🎯", "fléchettes", "le freccette"),
                EmojiWord("🎲", "dés", "i dadi")
            )),
            EmojiCategory("Technologie", "💾", listOf(
                EmojiWord("💾", "disque", "il disco"),
                EmojiWord("🖥️", "ordinateur fixe", "il computer fisso"),
                EmojiWord("⌨️", "clavier", "la tastiera"),
                EmojiWord("🖱️", "souris", "il mouse"),
                EmojiWord("📱", "smartphone", "lo smartphone"),
                EmojiWord("📶", "wifi", "il wifi"),
                EmojiWord("🔌", "prise", "la presa"),
                EmojiWord("🔋", "batterie", "la batteria"),
                EmojiWord("💿", "CD", "il CD")
            )),
            EmojiCategory("Météo", "🌤️", listOf(
                EmojiWord("☀️", "ensoleillé", "soleggiato"),
                EmojiWord("⛅", "nuageux", "nuvoloso"),
                EmojiWord("🌧️", "pluvieux", "piovoso"),
                EmojiWord("⛈️", "orageux", "temporalesco"),
                EmojiWord("🌨️", "neigeux", "nevoso"),
                EmojiWord("🌬️", "venteux", "ventoso"),
                EmojiWord("🌫️", "brumeux", "nebbioso"),
                EmojiWord("🌡️", "température", "la temperatura")
            )),
            EmojiCategory("Fêtes", "🎉", listOf(
                EmojiWord("🎉", "fête", "la festa"),
                EmojiWord("🎂", "anniversaire", "il compleanno"),
                EmojiWord("🎄", "Noël", "Natale"),
                EmojiWord("🎃", "Halloween", "Halloween"),
                EmojiWord("🎆", "feu d'artifice", "i fuochi d'artificio"),
                EmojiWord("🎊", "confettis", "i coriandoli"),
                EmojiWord("🎁", "cadeau", "il regalo"),
                EmojiWord("🎈", "ballon", "il palloncino")
            )),
            EmojiCategory("Nombres", "🔢", listOf(
                EmojiWord("0️⃣", "zéro", "zero"),
                EmojiWord("1️⃣", "un", "uno"),
                EmojiWord("2️⃣", "deux", "due"),
                EmojiWord("3️⃣", "trois", "tre"),
                EmojiWord("4️⃣", "quatre", "quattro"),
                EmojiWord("5️⃣", "cinq", "cinque"),
                EmojiWord("6️⃣", "six", "sei"),
                EmojiWord("7️⃣", "sept", "sette"),
                EmojiWord("8️⃣", "huit", "otto"),
                EmojiWord("9️⃣", "neuf", "nove"),
                EmojiWord("🔟", "dix", "dieci"),
                EmojiWord("💯", "cent", "cento"),
                EmojiWord("🔢", "nombre", "il numero"),
                EmojiWord("➕", "plus", "più"),
                EmojiWord("➖", "moins", "meno")
            )),
            EmojiCategory("Calendrier", "📆", listOf(
                EmojiWord("📆", "lundi", "lunedì"),
                EmojiWord("📅", "mardi", "martedì"),
                EmojiWord("🗓️", "mercredi", "mercoledì"),
                EmojiWord("📋", "jeudi", "giovedì"),
                EmojiWord("📃", "vendredi", "venerdì"),
                EmojiWord("📄", "samedi", "sabato"),
                EmojiWord("🗒️", "dimanche", "domenica"),
                EmojiWord("🌸", "printemps", "la primavera"),
                EmojiWord("☀️", "été", "l'estate"),
                EmojiWord("🍂", "automne", "l'autunno"),
                EmojiWord("❄️", "hiver", "l'inverno"),
                EmojiWord("📅", "janvier", "gennaio"),
                EmojiWord("💕", "février", "febbraio"),
                EmojiWord("🌷", "mars", "marzo"),
                EmojiWord("🌼", "avril", "aprile"),
                EmojiWord("🌺", "mai", "maggio"),
                EmojiWord("🌻", "juin", "giugno"),
                EmojiWord("🏖️", "juillet", "luglio"),
                EmojiWord("🌞", "août", "agosto"),
                EmojiWord("🍁", "septembre", "settembre"),
                EmojiWord("🎃", "octobre", "ottobre"),
                EmojiWord("🍂", "novembre", "novembre"),
                EmojiWord("🎄", "décembre", "dicembre")
            )),
            EmojiCategory("Sentiments", "💖", listOf(
                EmojiWord("❤️", "amour", "l'amore"),
                EmojiWord("💔", "cœur brisé", "il cuore spezzato"),
                EmojiWord("💖", "affection", "l'affetto"),
                EmojiWord("😊", "joie", "la gioia"),
                EmojiWord("😢", "tristesse", "la tristezza"),
                EmojiWord("😰", "peur", "la paura"),
                EmojiWord("😡", "colère", "la rabbia"),
                EmojiWord("😌", "paix", "la pace"),
                EmojiWord("🤗", "tendresse", "la tenerezza"),
                EmojiWord("😳", "surprise", "la sorpresa"),
                EmojiWord("😔", "déception", "la delusione"),
                EmojiWord("🥰", "bonheur", "la felicità"),
                EmojiWord("😤", "jalousie", "la gelosia"),
                EmojiWord("😨", "anxiété", "l'ansia")
            )),
            EmojiCategory("Adjectifs Utiles", "⭐", listOf(
                EmojiWord("😀", "heureux", "felice"),
                EmojiWord("😢", "triste", "triste"),
                EmojiWord("💪", "fort", "forte"),
                EmojiWord("🤏", "petit", "piccolo"),
                EmojiWord("🏔️", "grand", "grande"),
                EmojiWord("🔥", "chaud", "caldo"),
                EmojiWord("❄️", "froid", "freddo"),
                EmojiWord("✨", "beau", "bello"),
                EmojiWord("👎", "mauvais", "cattivo"),
                EmojiWord("👍", "bon", "buono"),
                EmojiWord("🐌", "lent", "lento"),
                EmojiWord("🚀", "rapide", "veloce"),
                EmojiWord("😴", "fatigué", "stanco"),
                EmojiWord("⚡", "énergique", "energico"),
                EmojiWord("🔊", "bruyant", "rumoroso"),
                EmojiWord("🔇", "silencieux", "silenzioso"),
                EmojiWord("💰", "riche", "ricco"),
                EmojiWord("💸", "pauvre", "povero"),
                EmojiWord("🧠", "intelligent", "intelligente"),
                EmojiWord("😵", "confus", "confuso")
            )),
            EmojiCategory("Verbes Essentiels", "🎬", listOf(
                EmojiWord("👋", "saluer", "salutare"),
                EmojiWord("🗣️", "parler", "parlare"),
                EmojiWord("👂", "écouter", "ascoltare"),
                EmojiWord("👀", "regarder", "guardare"),
                EmojiWord("🤝", "donner", "dare"),
                EmojiWord("✋", "prendre", "prendere"),
                EmojiWord("🚶", "aller", "andare"),
                EmojiWord("🔙", "venir", "venire"),
                EmojiWord("💭", "penser", "pensare"),
                EmojiWord("🧠", "comprendre", "capire"),
                EmojiWord("❤️", "aimer", "amare"),
                EmojiWord("💔", "détester", "odiare"),
                EmojiWord("🙏", "demander", "chiedere"),
                EmojiWord("💬", "répondre", "rispondere"),
                EmojiWord("🎓", "apprendre", "imparare"),
                EmojiWord("📖", "étudier", "studiare"),
                EmojiWord("💼", "travailler", "lavorare"),
                EmojiWord("😴", "se reposer", "riposare")
            )),
            EmojiCategory("Expressions Courantes", "💬", listOf(
                EmojiWord("👋", "bonjour", "ciao"),
                EmojiWord("👋🌅", "bonjour (matin)", "buongiorno"),
                EmojiWord("🌆", "bonsoir", "buonasera"),
                EmojiWord("😴🌙", "bonne nuit", "buonanotte"),
                EmojiWord("👋👋", "au revoir", "arrivederci"),
                EmojiWord("🙏", "s'il vous plaît", "per favore"),
                EmojiWord("🙏❤️", "merci", "grazie"),
                EmojiWord("👍", "de rien", "prego"),
                EmojiWord("😔", "pardon", "scusa"),
                EmojiWord("❓", "comment ça va?", "come stai?"),
                EmojiWord("👍", "bien", "bene"),
                EmojiWord("👎", "mal", "male"),
                EmojiWord("❓❔", "pourquoi?", "perché?"),
                EmojiWord("❓📍", "où?", "dove?"),
                EmojiWord("❓⏰", "quand?", "quando?"),
                EmojiWord("❓👤", "qui?", "chi?"),
                EmojiWord("❓🤔", "quoi?", "cosa?"),
                EmojiWord("✅", "oui", "sì"),
                EmojiWord("❌", "non", "no"),
                EmojiWord("🤷", "peut-être", "forse")
            )),
            EmojiCategory("Cuisine", "🍳", listOf(
                EmojiWord("🍳", "petit-déjeuner", "la colazione"),
                EmojiWord("🍽️", "déjeuner", "il pranzo"),
                EmojiWord("🌙🍽️", "dîner", "la cena"),
                EmojiWord("🥄", "cuillère", "il cucchiaio"),
                EmojiWord("🍴", "fourchette", "la forchetta"),
                EmojiWord("🔪", "couteau", "il coltello"),
                EmojiWord("🍽️", "assiette", "il piatto"),
                EmojiWord("🥛", "verre", "il bicchiere"),
                EmojiWord("☕", "tasse", "la tazza"),
                EmojiWord("🍳", "cuisiner", "cucinare"),
                EmojiWord("🔥", "bouillir", "bollire"),
                EmojiWord("🍞🔥", "griller", "grigliare"),
                EmojiWord("🧂", "sel", "il sale"),
                EmojiWord("🌶️", "poivre", "il pepe"),
                EmojiWord("🍯", "sucre", "lo zucchero"),
                EmojiWord("🧈", "beurre", "il burro"),
                EmojiWord("🥛", "lait", "il latte"),
                EmojiWord("💧", "eau", "l'acqua")
            )),
            EmojiCategory("Santé & Bien-être", "🏥", listOf(
                EmojiWord("🏥", "hôpital", "l'ospedale"),
                EmojiWord("💊", "médicament", "la medicina"),
                EmojiWord("💉", "injection", "l'iniezione"),
                EmojiWord("🩹", "pansement", "il cerotto"),
                EmojiWord("🌡️", "thermomètre", "il termometro"),
                EmojiWord("🩺", "stéthoscope", "lo stetoscopio"),
                EmojiWord("🦷", "dentiste", "il dentista"),
                EmojiWord("🧴", "crème", "la crema"),
                EmojiWord("🧼", "savon", "il sapone"),
                EmojiWord("🪥", "brosse à dents", "lo spazzolino"),
                EmojiWord("🧻", "papier toilette", "la carta igienica"),
                EmojiWord("🧽", "hygiène", "l'igiene"),
                EmojiWord("🚑", "ambulance", "l'ambulanza"),
                EmojiWord("⚕️", "soins", "le cure"),
                EmojiWord("💪", "santé", "la salute")
            )),
            EmojiCategory("Voyage & Tourisme", "✈️", listOf(
                EmojiWord("✈️", "voyage", "il viaggio"),
                EmojiWord("🧳", "valise", "la valigia"),
                EmojiWord("🎫", "billet", "il biglietto"),
                EmojiWord("🗺️", "carte", "la mappa"),
                EmojiWord("📍", "destination", "la destinazione"),
                EmojiWord("🏨", "hôtel", "l'albergo"),
                EmojiWord("🏖️", "vacances", "le vacanze"),
                EmojiWord("📸", "photo", "la foto"),
                EmojiWord("🎒", "sac à dos", "lo zaino"),
                EmojiWord("🧭", "boussole", "la bussola"),
                EmojiWord("🗼", "monument", "il monumento"),
                EmojiWord("🏛️", "tourisme", "il turismo"),
                EmojiWord("🛂", "passeport", "il passaporto"),
                EmojiWord("🛄", "bagages", "i bagagli"),
                EmojiWord("🏝️", "île", "l'isola")
            )),
            EmojiCategory("Argent & Shopping", "💰", listOf(
                EmojiWord("💰", "argent", "i soldi"),
                EmojiWord("💵", "billet", "la banconota"),
                EmojiWord("💳", "carte bancaire", "la carta di credito"),
                EmojiWord("🏦", "banque", "la banca"),
                EmojiWord("💸", "dépenser", "spendere"),
                EmojiWord("💲", "prix", "il prezzo"),
                EmojiWord("🛒", "caddie", "il carrello"),
                EmojiWord("🛍️", "shopping", "lo shopping"),
                EmojiWord("🏪", "boutique", "il negozio"),
                EmojiWord("💎", "cher", "costoso"),
                EmojiWord("🔖", "promotion", "la promozione"),
                EmojiWord("🧾", "reçu", "lo scontrino"),
                EmojiWord("💰", "économiser", "risparmiare"),
                EmojiWord("🤑", "riche", "ricco"),
                EmojiWord("📊", "compte", "il conto")
            )),
            EmojiCategory("Communication", "📱", listOf(
                EmojiWord("📱", "appeler", "chiamare"),
                EmojiWord("💬", "message", "il messaggio"),
                EmojiWord("📧", "email", "l'email"),
                EmojiWord("📬", "courrier", "la posta"),
                EmojiWord("📮", "boîte aux lettres", "la cassetta postale"),
                EmojiWord("📞", "téléphone", "il telefono"),
                EmojiWord("🔔", "notification", "la notifica"),
                EmojiWord("📣", "annoncer", "annunciare"),
                EmojiWord("📢", "crier", "gridare"),
                EmojiWord("🗣️", "discuter", "discutere"),
                EmojiWord("💭", "penser", "pensare"),
                EmojiWord("🗨️", "conversation", "la conversazione"),
                EmojiWord("📝", "écrire", "scrivere"),
                EmojiWord("✉️", "lettre", "la lettera"),
                EmojiWord("📲", "contacter", "contattare")
            )),
            EmojiCategory("Géographie & Pays", "🌍", listOf(
                EmojiWord("🌍", "monde", "il mondo"),
                EmojiWord("🗺️", "continent", "il continente"),
                EmojiWord("🇮🇹", "Italie", "l'Italia"),
                EmojiWord("🇪🇸", "Espagne", "la Spagna"),
                EmojiWord("🇫🇷", "France", "la Francia"),
                EmojiWord("🇬🇧", "Angleterre", "l'Inghilterra"),
                EmojiWord("🇩🇪", "Allemagne", "la Germania"),
                EmojiWord("🇺🇸", "États-Unis", "gli Stati Uniti"),
                EmojiWord("🏙️", "capitale", "la capitale"),
                EmojiWord("🗾", "pays", "il paese"),
                EmojiWord("🌐", "international", "internazionale"),
                EmojiWord("🧳", "voyager", "viaggiare"),
                EmojiWord("🛫", "partir", "partire"),
                EmojiWord("🛬", "arriver", "arrivare"),
                EmojiWord("🌏", "étranger", "straniero")
            )),
            EmojiCategory("Musique & Arts", "🎵", listOf(
                EmojiWord("🎵", "musique", "la musica"),
                EmojiWord("🎶", "chanson", "la canzone"),
                EmojiWord("🎤", "chanteur", "il cantante"),
                EmojiWord("🎸", "guitare", "la chitarra"),
                EmojiWord("🎹", "piano", "il pianoforte"),
                EmojiWord("🥁", "batterie", "la batteria"),
                EmojiWord("🎺", "trompette", "la tromba"),
                EmojiWord("🎻", "violon", "il violino"),
                EmojiWord("🎨", "art", "l'arte"),
                EmojiWord("🖼️", "peinture", "il quadro"),
                EmojiWord("🎭", "théâtre", "il teatro"),
                EmojiWord("🎬", "cinéma", "il cinema"),
                EmojiWord("🎪", "spectacle", "lo spettacolo"),
                EmojiWord("📷", "photographie", "la fotografia"),
                EmojiWord("🎼", "composer", "comporre")
            ))
        )
    }
    
    private fun getSpanishEmojis(): List<EmojiCategory> {
        return listOf(
            EmojiCategory("Émotions", "😊", listOf(
                EmojiWord("😀", "content", "contento"),
                EmojiWord("😢", "triste", "triste"),
                EmojiWord("😡", "en colère", "enfadado"),
                EmojiWord("😱", "effrayé", "asustado"),
                EmojiWord("😍", "amoureux", "enamorado"),
                EmojiWord("🤔", "pensif", "pensativo"),
                EmojiWord("😴", "fatigué", "cansado"),
                EmojiWord("🤢", "malade", "enfermo"),
                EmojiWord("😎", "cool", "guay"),
                EmojiWord("🥳", "festif", "festivo"),
                EmojiWord("😤", "frustré", "frustrado"),
                EmojiWord("🥺", "suppliant", "suplicante"),
                EmojiWord("🤩", "impressionné", "impresionado"),
                EmojiWord("😭", "en larmes", "llorando"),
                EmojiWord("😇", "sage", "bueno"),
                EmojiWord("🤗", "câlin", "abrazo"),
                EmojiWord("😏", "malin", "astuto"),
                EmojiWord("🥱", "bâillant", "bostezando"),
                EmojiWord("😵", "étourdi", "mareado"),
                EmojiWord("🤪", "fou", "loco")
            )),
            EmojiCategory("Nourriture", "🍕", listOf(
                EmojiWord("🍕", "pizza", "la pizza"),
                EmojiWord("🍝", "pâtes", "la pasta"),
                EmojiWord("🍞", "pain", "el pan"),
                EmojiWord("🧀", "fromage", "el queso"),
                EmojiWord("🍷", "vin", "el vino"),
                EmojiWord("☕", "café", "el café"),
                EmojiWord("🍦", "glace", "el helado"),
                EmojiWord("🍎", "pomme", "la manzana"),
                EmojiWord("🍊", "orange", "la naranja"),
                EmojiWord("🍋", "citron", "el limón"),
                EmojiWord("🍇", "raisin", "la uva"),
                EmojiWord("🍓", "fraise", "la fresa"),
                EmojiWord("🥕", "carotte", "la zanahoria"),
                EmojiWord("🥒", "concombre", "el pepino"),
                EmojiWord("🍅", "tomate", "el tomate"),
                EmojiWord("🥚", "œuf", "el huevo"),
                EmojiWord("🍌", "banane", "el plátano"),
                EmojiWord("🍰", "gâteau", "el pastel"),
                EmojiWord("🍟", "frites", "las patatas fritas"),
                EmojiWord("🍔", "hamburger", "la hamburguesa"),
                EmojiWord("🌮", "taco", "el taco"),
                EmojiWord("🍿", "pop-corn", "las palomitas"),
                EmojiWord("🍩", "donut", "la dona"),
                EmojiWord("🍪", "cookie", "la galleta"),
                EmojiWord("🥐", "croissant", "el cruasán")
            )),
            EmojiCategory("Animaux", "🐱", listOf(
                EmojiWord("🐱", "chat", "el gato"),
                EmojiWord("🐶", "chien", "el perro"),
                EmojiWord("🐦", "oiseau", "el pájaro"),
                EmojiWord("🐟", "poisson", "el pez"),
                EmojiWord("🐴", "cheval", "el caballo"),
                EmojiWord("🐄", "vache", "la vaca"),
                EmojiWord("🐷", "cochon", "el cerdo"),
                EmojiWord("🐑", "mouton", "la oveja"),
                EmojiWord("🐓", "coq", "el gallo"),
                EmojiWord("🦋", "papillon", "la mariposa"),
                EmojiWord("🐝", "abeille", "la abeja"),
                EmojiWord("🐢", "tortue", "la tortuga"),
                EmojiWord("🐘", "éléphant", "el elefante"),
                EmojiWord("🦁", "lion", "el león"),
                EmojiWord("🐻", "ours", "el oso"),
                EmojiWord("🐰", "lapin", "el conejo"),
                EmojiWord("🦊", "renard", "el zorro"),
                EmojiWord("🐯", "tigre", "el tigre"),
                EmojiWord("🦒", "girafe", "la jirafa"),
                EmojiWord("🐼", "panda", "el panda"),
                EmojiWord("🐨", "koala", "el koala"),
                EmojiWord("🦘", "kangourou", "el canguro"),
                EmojiWord("🐸", "grenouille", "la rana"),
                EmojiWord("🐍", "serpent", "la serpiente")
            )),
            EmojiCategory("Nature", "🌳", listOf(
                EmojiWord("🌳", "arbre", "el árbol"),
                EmojiWord("🌸", "fleur", "la flor"),
                EmojiWord("🌞", "soleil", "el sol"),
                EmojiWord("🌙", "lune", "la luna"),
                EmojiWord("⭐", "étoile", "la estrella"),
                EmojiWord("🌧️", "pluie", "la lluvia"),
                EmojiWord("❄️", "neige", "la nieve"),
                EmojiWord("🌈", "arc-en-ciel", "el arcoíris"),
                EmojiWord("🌊", "vague", "la ola"),
                EmojiWord("⛰️", "montagne", "la montaña"),
                EmojiWord("🏝️", "île", "la isla"),
                EmojiWord("🌴", "palmier", "la palmera"),
                EmojiWord("🌵", "cactus", "el cactus"),
                EmojiWord("🌺", "hibiscus", "el hibisco"),
                EmojiWord("🌻", "tournesol", "el girasol"),
                EmojiWord("🌹", "rose", "la rosa"),
                EmojiWord("🍀", "trèfle", "el trébol"),
                EmojiWord("🍁", "érable", "el arce"),
                EmojiWord("🌾", "blé", "el trigo")
            )),
            EmojiCategory("Transports", "🚗", listOf(
                EmojiWord("🚗", "voiture", "el coche"),
                EmojiWord("🚌", "bus", "el autobús"),
                EmojiWord("🚂", "train", "el tren"),
                EmojiWord("✈️", "avion", "el avión"),
                EmojiWord("🚢", "bateau", "el barco"),
                EmojiWord("🚲", "vélo", "la bicicleta"),
                EmojiWord("🏍️", "moto", "la moto"),
                EmojiWord("🚁", "hélicoptère", "el helicóptero"),
                EmojiWord("🚀", "fusée", "el cohete"),
                EmojiWord("🛴", "trottinette", "el patinete"),
                EmojiWord("🚕", "taxi", "el taxi"),
                EmojiWord("🚙", "SUV", "el todoterreno"),
                EmojiWord("🚎", "trolleybus", "el trolebús")
            )),
            EmojiCategory("Objets", "📱", listOf(
                EmojiWord("📱", "téléphone", "el teléfono"),
                EmojiWord("💻", "ordinateur", "el ordenador"),
                EmojiWord("📺", "télévision", "la televisión"),
                EmojiWord("📷", "appareil photo", "la cámara"),
                EmojiWord("🎸", "guitare", "la guitarra"),
                EmojiWord("🎹", "piano", "el piano"),
                EmojiWord("📚", "livres", "los libros"),
                EmojiWord("✏️", "crayon", "el lápiz"),
                EmojiWord("🔑", "clé", "la llave"),
                EmojiWord("💡", "ampoule", "la bombilla"),
                EmojiWord("🕶️", "lunettes", "las gafas"),
                EmojiWord("👜", "sac", "el bolso"),
                EmojiWord("⌚", "montre", "el reloj"),
                EmojiWord("💍", "bague", "el anillo"),
                EmojiWord("👑", "couronne", "la corona"),
                EmojiWord("🎁", "cadeau", "el regalo"),
                EmojiWord("🎈", "ballon", "el globo"),
                EmojiWord("🔦", "lampe", "la linterna")
            )),
            EmojiCategory("Sports", "⚽", listOf(
                EmojiWord("⚽", "football", "el fútbol"),
                EmojiWord("🏀", "basketball", "el baloncesto"),
                EmojiWord("🎾", "tennis", "el tenis"),
                EmojiWord("🏊", "natation", "la natación"),
                EmojiWord("🚴", "cyclisme", "el ciclismo"),
                EmojiWord("⛷️", "ski", "el esquí"),
                EmojiWord("🏃", "course", "la carrera"),
                EmojiWord("🥊", "boxe", "el boxeo"),
                EmojiWord("🏐", "volleyball", "el voleibol"),
                EmojiWord("🏈", "football américain", "el fútbol americano"),
                EmojiWord("⛳", "golf", "el golf"),
                EmojiWord("🎿", "ski", "el esquí")
            )),
            EmojiCategory("Lieux", "🏠", listOf(
                EmojiWord("🏠", "maison", "la casa"),
                EmojiWord("🏫", "école", "la escuela"),
                EmojiWord("🏥", "hôpital", "el hospital"),
                EmojiWord("🏪", "magasin", "la tienda"),
                EmojiWord("🏦", "banque", "el banco"),
                EmojiWord("⛪", "église", "la iglesia"),
                EmojiWord("🏰", "château", "el castillo"),
                EmojiWord("🏖️", "plage", "la playa"),
                EmojiWord("🎭", "théâtre", "el teatro"),
                EmojiWord("🎢", "parc d'attractions", "el parque de atracciones"),
                EmojiWord("🏛️", "musée", "el museo"),
                EmojiWord("🏨", "hôtel", "el hotel"),
                EmojiWord("🏟️", "stade", "el estadio")
            )),
            EmojiCategory("Corps", "👁️", listOf(
                EmojiWord("👁️", "œil", "el ojo"),
                EmojiWord("👂", "oreille", "la oreja"),
                EmojiWord("👃", "nez", "la nariz"),
                EmojiWord("👄", "bouche", "la boca"),
                EmojiWord("🦷", "dent", "el diente"),
                EmojiWord("👅", "langue", "la lengua"),
                EmojiWord("✋", "main", "la mano"),
                EmojiWord("🦶", "pied", "el pie"),
                EmojiWord("❤️", "cœur", "el corazón"),
                EmojiWord("🧠", "cerveau", "el cerebro"),
                EmojiWord("🦴", "os", "el hueso"),
                EmojiWord("💪", "muscle", "el músculo")
            )),
            EmojiCategory("Métiers", "👨‍⚕️", listOf(
                EmojiWord("👨‍⚕️", "médecin", "el médico"),
                EmojiWord("👨‍🏫", "professeur", "el profesor"),
                EmojiWord("👨‍🍳", "cuisinier", "el cocinero"),
                EmojiWord("👨‍🚒", "pompier", "el bombero"),
                EmojiWord("👮", "policier", "el policía"),
                EmojiWord("👨‍🌾", "agriculteur", "el agricultor"),
                EmojiWord("👨‍🔧", "mécanicien", "el mecánico"),
                EmojiWord("👨‍💼", "homme d'affaires", "el empresario"),
                EmojiWord("👨‍⚖️", "juge", "el juez"),
                EmojiWord("👨‍🎨", "artiste", "el artista"),
                EmojiWord("👨‍✈️", "pilote", "el piloto")
            )),
            EmojiCategory("Temps", "⏰", listOf(
                EmojiWord("⏰", "heure", "la hora"),
                EmojiWord("📅", "jour", "el día"),
                EmojiWord("🌅", "matin", "la mañana"),
                EmojiWord("🌇", "soir", "la tarde"),
                EmojiWord("🌃", "nuit", "la noche"),
                EmojiWord("📆", "semaine", "la semana"),
                EmojiWord("🗓️", "mois", "el mes"),
                EmojiWord("🎆", "année", "el año"),
                EmojiWord("⏱️", "chronomètre", "el cronómetro"),
                EmojiWord("⌛", "sablier", "el reloj de arena")
            )),
            EmojiCategory("Actions", "🏃", listOf(
                EmojiWord("🚶", "marcher", "caminar"),
                EmojiWord("🏃", "courir", "correr"),
                EmojiWord("🏊", "nager", "nadar"),
                EmojiWord("💤", "dormir", "dormir"),
                EmojiWord("🍽️", "manger", "comer"),
                EmojiWord("🥤", "boire", "beber"),
                EmojiWord("📖", "lire", "leer"),
                EmojiWord("✍️", "écrire", "escribir"),
                EmojiWord("🎤", "chanter", "cantar"),
                EmojiWord("💃", "danser", "bailar"),
                EmojiWord("👏", "applaudir", "aplaudir"),
                EmojiWord("🧹", "nettoyer", "limpiar"),
                EmojiWord("🧺", "faire la lessive", "lavar la ropa"),
                EmojiWord("🛌", "se coucher", "acostarse"),
                EmojiWord("🚿", "se doucher", "ducharse")
            )),
            EmojiCategory("Vêtements", "👕", listOf(
                EmojiWord("👕", "t-shirt", "la camiseta"),
                EmojiWord("👖", "pantalon", "los pantalones"),
                EmojiWord("👗", "robe", "el vestido"),
                EmojiWord("🧥", "manteau", "el abrigo"),
                EmojiWord("🧢", "casquette", "la gorra"),
                EmojiWord("👟", "chaussures", "los zapatos"),
                EmojiWord("🧦", "chaussettes", "los calcetines"),
                EmojiWord("👔", "cravate", "la corbata"),
                EmojiWord("👠", "talons", "los tacones"),
                EmojiWord("👜", "sac à main", "el bolso de mano")
            )),
            EmojiCategory("Couleurs", "🎨", listOf(
                EmojiWord("🔴", "rouge", "rojo"),
                EmojiWord("🔵", "bleu", "azul"),
                EmojiWord("🟢", "vert", "verde"),
                EmojiWord("🟡", "jaune", "amarillo"),
                EmojiWord("⚫", "noir", "negro"),
                EmojiWord("⚪", "blanc", "blanco"),
                EmojiWord("🟠", "orange", "naranja"),
                EmojiWord("🌸", "rose", "rosa"),
                EmojiWord("🟣", "violet", "morado"),
                EmojiWord("🟤", "marron", "marrón")
            )),
            EmojiCategory("Famille", "👨‍👩‍👧‍👦", listOf(
                EmojiWord("👩", "mère", "la madre"),
                EmojiWord("👨", "père", "el padre"),
                EmojiWord("👦", "fils", "el hijo"),
                EmojiWord("👧", "fille", "la hija"),
                EmojiWord("🧒", "enfant", "el niño"),
                EmojiWord("👵", "grand-mère", "la abuela"),
                EmojiWord("👴", "grand-père", "el abuelo"),
                EmojiWord("👨‍👩‍👧‍👦", "famille", "la familia"),
                EmojiWord("👶", "bébé", "el bebé"),
                EmojiWord("🧑", "personne", "la persona")
            )),
            EmojiCategory("Maison", "🏡", listOf(
                EmojiWord("🏡", "maison", "la casa"),
                EmojiWord("🛏️", "lit", "la cama"),
                EmojiWord("🚿", "douche", "la ducha"),
                EmojiWord("🚪", "porte", "la puerta"),
                EmojiWord("🪑", "chaise", "la silla"),
                EmojiWord("🪟", "fenêtre", "la ventana"),
                EmojiWord("🧽", "éponge", "la esponja"),
                EmojiWord("🛋️", "canapé", "el sofá"),
                EmojiWord("🍽️", "table", "la mesa"),
                EmojiWord("🚽", "toilettes", "el baño")
            )),
            EmojiCategory("École", "🎓", listOf(
                EmojiWord("🎓", "école", "la escuela"),
                EmojiWord("🎒", "sac à dos", "la mochila"),
                EmojiWord("📚", "livres", "los libros"),
                EmojiWord("✏️", "crayon", "el lápiz"),
                EmojiWord("🖊️", "stylo", "el bolígrafo"),
                EmojiWord("🧮", "calculatrice", "la calculadora"),
                EmojiWord("🧑‍🏫", "professeur", "el profesor"),
                EmojiWord("📐", "règle", "la regla"),
                EmojiWord("✂️", "ciseaux", "las tijeras"),
                EmojiWord("📝", "note", "la nota")
            )),
            EmojiCategory("Ville", "🏙️", listOf(
                EmojiWord("🏙️", "ville", "la ciudad"),
                EmojiWord("🏬", "centre commercial", "el centro comercial"),
                EmojiWord("🚇", "métro", "el metro"),
                EmojiWord("🏢", "immeuble", "el edificio"),
                EmojiWord("🌉", "pont", "el puente"),
                EmojiWord("🚦", "feu rouge", "el semáforo"),
                EmojiWord("🏩", "love hotel", "el motel"),
                EmojiWord("🚏", "arrêt de bus", "la parada")
            )),
            EmojiCategory("Loisirs", "🧸", listOf(
                EmojiWord("🎮", "jeu vidéo", "el videojuego"),
                EmojiWord("🎨", "dessin", "el dibujo"),
                EmojiWord("🎧", "musique", "la música"),
                EmojiWord("🎬", "film", "la película"),
                EmojiWord("📺", "série", "la serie"),
                EmojiWord("🧸", "jouet", "el juguete"),
                EmojiWord("🎪", "cirque", "el circo"),
                EmojiWord("🎯", "fléchettes", "los dardos"),
                EmojiWord("🎲", "dés", "los dados")
            )),
            EmojiCategory("Technologie", "💾", listOf(
                EmojiWord("💾", "disque", "el disco"),
                EmojiWord("🖥️", "ordinateur fixe", "el ordenador de sobremesa"),
                EmojiWord("⌨️", "clavier", "el teclado"),
                EmojiWord("🖱️", "souris", "el ratón"),
                EmojiWord("📱", "smartphone", "el móvil"),
                EmojiWord("📶", "wifi", "el wifi"),
                EmojiWord("🔌", "prise", "el enchufe"),
                EmojiWord("🔋", "batterie", "la batería"),
                EmojiWord("💿", "CD", "el CD")
            )),
            EmojiCategory("Météo", "🌤️", listOf(
                EmojiWord("☀️", "ensoleillé", "soleado"),
                EmojiWord("⛅", "nuageux", "nublado"),
                EmojiWord("🌧️", "pluvieux", "lluvioso"),
                EmojiWord("⛈️", "orageux", "tormentoso"),
                EmojiWord("🌨️", "neigeux", "nevado"),
                EmojiWord("🌬️", "venteux", "ventoso"),
                EmojiWord("🌫️", "brumeux", "neblinoso"),
                EmojiWord("🌡️", "température", "la temperatura")
            )),
            EmojiCategory("Fêtes", "🎉", listOf(
                EmojiWord("🎉", "fête", "la fiesta"),
                EmojiWord("🎂", "anniversaire", "el cumpleaños"),
                EmojiWord("🎄", "Noël", "Navidad"),
                EmojiWord("🎃", "Halloween", "Halloween"),
                EmojiWord("🎆", "feu d'artifice", "los fuegos artificiales"),
                EmojiWord("🎊", "confettis", "el confeti"),
                EmojiWord("🎁", "cadeau", "el regalo"),
                EmojiWord("🎈", "ballon", "el globo")
            )),
            EmojiCategory("Nombres", "🔢", listOf(
                EmojiWord("0️⃣", "zéro", "cero"),
                EmojiWord("1️⃣", "un", "uno"),
                EmojiWord("2️⃣", "deux", "dos"),
                EmojiWord("3️⃣", "trois", "tres"),
                EmojiWord("4️⃣", "quatre", "cuatro"),
                EmojiWord("5️⃣", "cinq", "cinco"),
                EmojiWord("6️⃣", "six", "seis"),
                EmojiWord("7️⃣", "sept", "siete"),
                EmojiWord("8️⃣", "huit", "ocho"),
                EmojiWord("9️⃣", "neuf", "nueve"),
                EmojiWord("🔟", "dix", "diez"),
                EmojiWord("💯", "cent", "cien"),
                EmojiWord("🔢", "nombre", "el número"),
                EmojiWord("➕", "plus", "más"),
                EmojiWord("➖", "moins", "menos")
            )),
            EmojiCategory("Calendrier", "📆", listOf(
                EmojiWord("📆", "lundi", "lunes"),
                EmojiWord("📅", "mardi", "martes"),
                EmojiWord("🗓️", "mercredi", "miércoles"),
                EmojiWord("📋", "jeudi", "jueves"),
                EmojiWord("📃", "vendredi", "viernes"),
                EmojiWord("📄", "samedi", "sábado"),
                EmojiWord("🗒️", "dimanche", "domingo"),
                EmojiWord("🌸", "printemps", "la primavera"),
                EmojiWord("☀️", "été", "el verano"),
                EmojiWord("🍂", "automne", "el otoño"),
                EmojiWord("❄️", "hiver", "el invierno"),
                EmojiWord("📅", "janvier", "enero"),
                EmojiWord("💕", "février", "febrero"),
                EmojiWord("🌷", "mars", "marzo"),
                EmojiWord("🌼", "avril", "abril"),
                EmojiWord("🌺", "mai", "mayo"),
                EmojiWord("🌻", "juin", "junio"),
                EmojiWord("🏖️", "juillet", "julio"),
                EmojiWord("🌞", "août", "agosto"),
                EmojiWord("🍁", "septembre", "septiembre"),
                EmojiWord("🎃", "octobre", "octubre"),
                EmojiWord("🍂", "novembre", "noviembre"),
                EmojiWord("🎄", "décembre", "diciembre")
            )),
            EmojiCategory("Sentiments", "💖", listOf(
                EmojiWord("❤️", "amour", "el amor"),
                EmojiWord("💔", "cœur brisé", "el corazón roto"),
                EmojiWord("💖", "affection", "el cariño"),
                EmojiWord("😊", "joie", "la alegría"),
                EmojiWord("😢", "tristesse", "la tristeza"),
                EmojiWord("😰", "peur", "el miedo"),
                EmojiWord("😡", "colère", "la ira"),
                EmojiWord("😌", "paix", "la paz"),
                EmojiWord("🤗", "tendresse", "la ternura"),
                EmojiWord("😳", "surprise", "la sorpresa"),
                EmojiWord("😔", "déception", "la decepción"),
                EmojiWord("🥰", "bonheur", "la felicidad"),
                EmojiWord("😤", "jalousie", "los celos"),
                EmojiWord("😨", "anxiété", "la ansiedad")
            )),
            EmojiCategory("Adjectifs Utiles", "⭐", listOf(
                EmojiWord("😀", "heureux", "feliz"),
                EmojiWord("😢", "triste", "triste"),
                EmojiWord("💪", "fort", "fuerte"),
                EmojiWord("🤏", "petit", "pequeño"),
                EmojiWord("🏔️", "grand", "grande"),
                EmojiWord("🔥", "chaud", "caliente"),
                EmojiWord("❄️", "froid", "frío"),
                EmojiWord("✨", "beau", "hermoso"),
                EmojiWord("👎", "mauvais", "malo"),
                EmojiWord("👍", "bon", "bueno"),
                EmojiWord("🐌", "lent", "lento"),
                EmojiWord("🚀", "rapide", "rápido"),
                EmojiWord("😴", "fatigué", "cansado"),
                EmojiWord("⚡", "énergique", "enérgico"),
                EmojiWord("🔊", "bruyant", "ruidoso"),
                EmojiWord("🔇", "silencieux", "silencioso"),
                EmojiWord("💰", "riche", "rico"),
                EmojiWord("💸", "pauvre", "pobre"),
                EmojiWord("🧠", "intelligent", "inteligente"),
                EmojiWord("😵", "confus", "confundido")
            )),
            EmojiCategory("Verbes Essentiels", "🎬", listOf(
                EmojiWord("👋", "saluer", "saludar"),
                EmojiWord("🗣️", "parler", "hablar"),
                EmojiWord("👂", "écouter", "escuchar"),
                EmojiWord("👀", "regarder", "mirar"),
                EmojiWord("🤝", "donner", "dar"),
                EmojiWord("✋", "prendre", "tomar"),
                EmojiWord("🚶", "aller", "ir"),
                EmojiWord("🔙", "venir", "venir"),
                EmojiWord("💭", "penser", "pensar"),
                EmojiWord("🧠", "comprendre", "entender"),
                EmojiWord("❤️", "aimer", "amar"),
                EmojiWord("💔", "détester", "odiar"),
                EmojiWord("🙏", "demander", "preguntar"),
                EmojiWord("💬", "répondre", "responder"),
                EmojiWord("🎓", "apprendre", "aprender"),
                EmojiWord("📖", "étudier", "estudiar"),
                EmojiWord("💼", "travailler", "trabajar"),
                EmojiWord("😴", "se reposer", "descansar")
            )),
            EmojiCategory("Expressions Courantes", "💬", listOf(
                EmojiWord("👋", "bonjour", "hola"),
                EmojiWord("👋🌅", "bonjour (matin)", "buenos días"),
                EmojiWord("🌆", "bonsoir", "buenas tardes"),
                EmojiWord("😴🌙", "bonne nuit", "buenas noches"),
                EmojiWord("👋👋", "au revoir", "adiós"),
                EmojiWord("🙏", "s'il vous plaît", "por favor"),
                EmojiWord("🙏❤️", "merci", "gracias"),
                EmojiWord("👍", "de rien", "de nada"),
                EmojiWord("😔", "pardon", "perdón"),
                EmojiWord("❓", "comment ça va?", "¿cómo estás?"),
                EmojiWord("👍", "bien", "bien"),
                EmojiWord("👎", "mal", "mal"),
                EmojiWord("❓❔", "pourquoi?", "¿por qué?"),
                EmojiWord("❓📍", "où?", "¿dónde?"),
                EmojiWord("❓⏰", "quand?", "¿cuándo?"),
                EmojiWord("❓👤", "qui?", "¿quién?"),
                EmojiWord("❓🤔", "quoi?", "¿qué?"),
                EmojiWord("✅", "oui", "sí"),
                EmojiWord("❌", "non", "no"),
                EmojiWord("🤷", "peut-être", "quizás")
            )),
            EmojiCategory("Cuisine", "🍳", listOf(
                EmojiWord("🍳", "petit-déjeuner", "el desayuno"),
                EmojiWord("🍽️", "déjeuner", "la comida"),
                EmojiWord("🌙🍽️", "dîner", "la cena"),
                EmojiWord("🥄", "cuillère", "la cuchara"),
                EmojiWord("🍴", "fourchette", "el tenedor"),
                EmojiWord("🔪", "couteau", "el cuchillo"),
                EmojiWord("🍽️", "assiette", "el plato"),
                EmojiWord("🥛", "verre", "el vaso"),
                EmojiWord("☕", "tasse", "la taza"),
                EmojiWord("🍳", "cuisiner", "cocinar"),
                EmojiWord("🔥", "bouillir", "hervir"),
                EmojiWord("🍞🔥", "griller", "asar"),
                EmojiWord("🧂", "sel", "la sal"),
                EmojiWord("🌶️", "poivre", "la pimienta"),
                EmojiWord("🍯", "sucre", "el azúcar"),
                EmojiWord("🧈", "beurre", "la mantequilla"),
                EmojiWord("🥛", "lait", "la leche"),
                EmojiWord("💧", "eau", "el agua")
            )),
            EmojiCategory("Santé & Bien-être", "🏥", listOf(
                EmojiWord("🏥", "hôpital", "el hospital"),
                EmojiWord("💊", "médicament", "la medicina"),
                EmojiWord("💉", "injection", "la inyección"),
                EmojiWord("🩹", "pansement", "la tirita"),
                EmojiWord("🌡️", "thermomètre", "el termómetro"),
                EmojiWord("🩺", "stéthoscope", "el estetoscopio"),
                EmojiWord("🦷", "dentiste", "el dentista"),
                EmojiWord("🧴", "crème", "la crema"),
                EmojiWord("🧼", "savon", "el jabón"),
                EmojiWord("🪥", "brosse à dents", "el cepillo de dientes"),
                EmojiWord("🧻", "papier toilette", "el papel higiénico"),
                EmojiWord("🧽", "hygiène", "la higiene"),
                EmojiWord("🚑", "ambulance", "la ambulancia"),
                EmojiWord("⚕️", "soins", "los cuidados"),
                EmojiWord("💪", "santé", "la salud")
            )),
            EmojiCategory("Voyage & Tourisme", "✈️", listOf(
                EmojiWord("✈️", "voyage", "el viaje"),
                EmojiWord("🧳", "valise", "la maleta"),
                EmojiWord("🎫", "billet", "el billete"),
                EmojiWord("🗺️", "carte", "el mapa"),
                EmojiWord("📍", "destination", "el destino"),
                EmojiWord("🏨", "hôtel", "el hotel"),
                EmojiWord("🏖️", "vacances", "las vacaciones"),
                EmojiWord("📸", "photo", "la foto"),
                EmojiWord("🎒", "sac à dos", "la mochila"),
                EmojiWord("🧭", "boussole", "la brújula"),
                EmojiWord("🗼", "monument", "el monumento"),
                EmojiWord("🏛️", "tourisme", "el turismo"),
                EmojiWord("🛂", "passeport", "el pasaporte"),
                EmojiWord("🛄", "bagages", "el equipaje"),
                EmojiWord("🏝️", "île", "la isla")
            )),
            EmojiCategory("Argent & Shopping", "💰", listOf(
                EmojiWord("💰", "argent", "el dinero"),
                EmojiWord("💵", "billet", "el billete"),
                EmojiWord("💳", "carte bancaire", "la tarjeta de crédito"),
                EmojiWord("🏦", "banque", "el banco"),
                EmojiWord("💸", "dépenser", "gastar"),
                EmojiWord("💲", "prix", "el precio"),
                EmojiWord("🛒", "caddie", "el carrito"),
                EmojiWord("🛍️", "shopping", "las compras"),
                EmojiWord("🏪", "boutique", "la tienda"),
                EmojiWord("💎", "cher", "caro"),
                EmojiWord("🔖", "promotion", "la oferta"),
                EmojiWord("🧾", "reçu", "el recibo"),
                EmojiWord("💰", "économiser", "ahorrar"),
                EmojiWord("🤑", "riche", "rico"),
                EmojiWord("📊", "compte", "la cuenta")
            )),
            EmojiCategory("Communication", "📱", listOf(
                EmojiWord("📱", "appeler", "llamar"),
                EmojiWord("💬", "message", "el mensaje"),
                EmojiWord("📧", "email", "el correo electrónico"),
                EmojiWord("📬", "courrier", "el correo"),
                EmojiWord("📮", "boîte aux lettres", "el buzón"),
                EmojiWord("📞", "téléphone", "el teléfono"),
                EmojiWord("🔔", "notification", "la notificación"),
                EmojiWord("📣", "annoncer", "anunciar"),
                EmojiWord("📢", "crier", "gritar"),
                EmojiWord("🗣️", "discuter", "discutir"),
                EmojiWord("💭", "penser", "pensar"),
                EmojiWord("🗨️", "conversation", "la conversación"),
                EmojiWord("📝", "écrire", "escribir"),
                EmojiWord("✉️", "lettre", "la carta"),
                EmojiWord("📲", "contacter", "contactar")
            )),
            EmojiCategory("Géographie & Pays", "🌍", listOf(
                EmojiWord("🌍", "monde", "el mundo"),
                EmojiWord("🗺️", "continent", "el continente"),
                EmojiWord("🇮🇹", "Italie", "Italia"),
                EmojiWord("🇪🇸", "Espagne", "España"),
                EmojiWord("🇫🇷", "France", "Francia"),
                EmojiWord("🇬🇧", "Angleterre", "Inglaterra"),
                EmojiWord("🇩🇪", "Allemagne", "Alemania"),
                EmojiWord("🇺🇸", "États-Unis", "Estados Unidos"),
                EmojiWord("🏙️", "capitale", "la capital"),
                EmojiWord("🗾", "pays", "el país"),
                EmojiWord("🌐", "international", "internacional"),
                EmojiWord("🧳", "voyager", "viajar"),
                EmojiWord("🛫", "partir", "salir"),
                EmojiWord("🛬", "arriver", "llegar"),
                EmojiWord("🌏", "étranger", "extranjero")
            )),
            EmojiCategory("Musique & Arts", "🎵", listOf(
                EmojiWord("🎵", "musique", "la música"),
                EmojiWord("🎶", "chanson", "la canción"),
                EmojiWord("🎤", "chanteur", "el cantante"),
                EmojiWord("🎸", "guitare", "la guitarra"),
                EmojiWord("🎹", "piano", "el piano"),
                EmojiWord("🥁", "batterie", "la batería"),
                EmojiWord("🎺", "trompette", "la trompeta"),
                EmojiWord("🎻", "violon", "el violín"),
                EmojiWord("🎨", "art", "el arte"),
                EmojiWord("🖼️", "peinture", "el cuadro"),
                EmojiWord("🎭", "théâtre", "el teatro"),
                EmojiWord("🎬", "cinéma", "el cine"),
                EmojiWord("🎪", "spectacle", "el espectáculo"),
                EmojiWord("📷", "photographie", "la fotografía"),
                EmojiWord("🎼", "composer", "componer")
            ))
        )
    }
    
    private fun getItalianStories(): List<EmojiStory> {
        return listOf(
            EmojiStory("it-breakfast", "🍞☕", "Je prends du pain et un café.", "Mangio il pane e bevo il caffè."),
            EmojiStory("it-school", "🏫🎒📚", "Je vais à l'école avec mon sac et mes livres.", "Vado a scuola con lo zaino e i libri."),
            EmojiStory("it-beach", "🏖️🌞🌊", "Nous sommes à la plage au soleil.", "Siamo in spiaggia al sole."),
            EmojiStory("it-sport", "⚽🏃🥤", "Je joue au foot et je bois de l'eau.", "Gioco a calcio e bevo acqua."),
            EmojiStory("it-family-dinner", "👨‍👩‍👧‍👦🍽️🏠", "Je dîne à la maison avec ma famille.", "Ceno a casa con la mia famiglia."),
            EmojiStory("it-travel", "🧳✈️🏨", "Je voyage en avion et je dors à l'hôtel.", "Viaggio in aereo e dormo in hotel.")
        )
    }
    
    private fun getSpanishStories(): List<EmojiStory> {
        return listOf(
            EmojiStory("es-breakfast", "🍞☕", "Je prends du pain et un café.", "Como pan y bebo café."),
            EmojiStory("es-school", "🏫🎒📚", "Je vais à l'école avec mon sac et mes livres.", "Voy a la escuela con la mochila y los libros."),
            EmojiStory("es-beach", "🏖️🌞🌊", "Nous sommes à la plage au soleil.", "Estamos en la playa al sol."),
            EmojiStory("es-sport", "⚽🏃🥤", "Je joue au foot et je bois de l'eau.", "Juego al fútbol y bebo agua."),
            EmojiStory("es-family-dinner", "👨‍👩‍👧‍👦🍽️🏠", "Je dîne à la maison avec ma famille.", "Ceno en casa con mi familia."),
            EmojiStory("es-travel", "🧳✈️🏨", "Je voyage en avion et je dors à l'hôtel.", "Viajo en avión y duermo en el hotel.")
        )
    }
}
